#define MA_NO_VERSIONING
#define MINIAUDIO_IMPLEMENTATION
#include "decoder.h"
// Include the autogenerated header
#include "_cgo_export.h"

/**
 * Initializes the audio resampler context (SwrContext).
 *
 * Media files contain various sample rates (e.g., 44.1kHz, 48kHz), formats (e.g., s16, s32, flt),
 * and channel layouts (e.g., Mono, Stereo, 5.1). Miniaudio requires a consistent and predictable
 * hardware format to route audio cleanly.
 *
 * This function standardizes any incoming audio stream to:
 *   - Sample Rate: 48,000 Hz (48kHz Studio Quality)
 *   - Channels: 2 Channels (Stereo)
 *   - Format: 32-bit Floating Point (highly compatible with miniaudio & modern sound cards)
 *
 * @param ctx   Pointer to the active DemuxDecContext tracking the audio decoder.
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int init_audio_resampler(DemuxDecContext *ctx)
{
  int ret;

  // Set normalized audio properties
  ctx->target_sample_rate = 48000;
  av_channel_layout_default(&ctx->target_ch_layout, 2); // Force standard Stereo (L/R)
  // CRITICAL FIX: AAC native encoder requires AV_SAMPLE_FMT_FLTP (Planar)
  ctx->target_sample_fmt = AV_SAMPLE_FMT_FLTP; // Force 32-bit float format

  // Allocate and configure the SwrContext using the modern channel layout API.
  // This calculates transition coefficients between the source and target formats.
  ret = swr_alloc_set_opts2(
      &ctx->swr_ctx,
      &ctx->target_ch_layout,          // Output channel layout
      ctx->target_sample_fmt,          // Output sample format (Float32)
      ctx->target_sample_rate,         // Output sample rate (48000 Hz)
      &ctx->audio_dec_ctx->ch_layout,  // Input channel layout (from source codec)
      ctx->audio_dec_ctx->sample_fmt,  // Input sample format (from source codec)
      ctx->audio_dec_ctx->sample_rate, // Input sample rate (from source codec)
      0, NULL);                        // No extra log offset parameters

  // Ensure allocation succeeded before proceeding
  if (ret < 0 || !ctx->swr_ctx)
  {
    return (ret < 0) ? ret : AVERROR(ENOMEM);
  }

  // Initialize the resampler context with the configured parameters
  ret = swr_init(ctx->swr_ctx);
  if (ret < 0)
  {
    swr_free(&ctx->swr_ctx);
    return ret;
  }

  return 0;
}

/**
 * Opens a media file, reads its metadata, and initializes the decoders
 * for both the primary video and audio streams.
 *
 * This function manages the safe, initial step-by-step pipeline discovery:
 *   1. Opens the media file container and parses headers.
 *   2. Extracts packet-level stream descriptors (resolution, codecs, sample rates).
 *   3. Locates the best video stream and opens its corresponding hardware-agnostic decoder.
 *   4. Locates the best audio stream, opens its decoder, and initializes the resampler.
 *
 * If any middle step fails, a unified "fail" label acts as an emergency sweep,
 * freeing partially allocated memory blocks to prevent structural leaks.
 *
 * @param ctx          Pointer to the uninitialized DemuxDecContext structure.
 * @param input_path   System file path to the source video (e.g., MKV, MP4).
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int open_input_and_decoders(DemuxDecContext *ctx, const char *input_path)
{
  int ret;
  ctx->fmt_ctx = NULL;
  ctx->video_stream_idx = -1;
  ctx->audio_stream_idx = -1;
  ctx->video_dec_ctx = NULL;
  ctx->audio_dec_ctx = NULL;
  ctx->swr_ctx = NULL;

  // 1. Open the media file container and extract initial stream parameters
  ret = avformat_open_input(&ctx->fmt_ctx, input_path, NULL, NULL);
  if (ret < 0)
    return ret;

  // 2. Query the stream contents of the container to discover streams
  ret = avformat_find_stream_info(ctx->fmt_ctx, NULL);
  if (ret < 0)
    goto fail;

  // 3. Find and configure the best Video Stream in the container
  const AVCodec *video_codec = NULL;
  ret = av_find_best_stream(ctx->fmt_ctx, AVMEDIA_TYPE_VIDEO, -1, -1, &video_codec, 0);
  if (ret >= 0)
  {
    ctx->video_stream_idx = ret;

    // Allocate raw codec context block
    ctx->video_dec_ctx = avcodec_alloc_context3(video_codec);
    if (!ctx->video_dec_ctx)
    {
      ret = AVERROR(ENOMEM);
      goto fail;
    }

    // Copy stream configurations (width, height, profiles) to the decoder context
    ret = avcodec_parameters_to_context(ctx->video_dec_ctx, ctx->fmt_ctx->streams[ctx->video_stream_idx]->codecpar);
    if (ret < 0)
      goto fail;

    // Initialize and open the decoder thread
    ret = avcodec_open2(ctx->video_dec_ctx, video_codec, NULL);
    if (ret < 0)
      goto fail;
  }

  // 4. Find and configure the best Audio Stream in the container
  const AVCodec *audio_codec = NULL;
  ret = av_find_best_stream(ctx->fmt_ctx, AVMEDIA_TYPE_AUDIO, -1, -1, &audio_codec, 0);
  if (ret >= 0)
  {
    ctx->audio_stream_idx = ret;

    // Allocate raw audio codec context block
    ctx->audio_dec_ctx = avcodec_alloc_context3(audio_codec);
    if (!ctx->audio_dec_ctx)
    {
      ret = AVERROR(ENOMEM);
      goto fail;
    }

    // Copy stream configurations (sample rate, bit-rate, channel layout) to the decoder context
    ret = avcodec_parameters_to_context(ctx->audio_dec_ctx, ctx->fmt_ctx->streams[ctx->audio_stream_idx]->codecpar);
    if (ret < 0)
      goto fail;

    // Initialize and open the audio decoder
    ret = avcodec_open2(ctx->audio_dec_ctx, audio_codec, NULL);
    if (ret < 0)
      goto fail;

    // Initialize swresample to normalize audio for miniaudio
    ret = init_audio_resampler(ctx);
    if (ret < 0)
      goto fail;
  }

  return 0;

fail:
  // Rollback phase: cleanly close allocations in reverse order of initialization
  if (ctx->video_dec_ctx)
    avcodec_free_context(&ctx->video_dec_ctx);
  if (ctx->audio_dec_ctx)
    avcodec_free_context(&ctx->audio_dec_ctx);
  if (ctx->fmt_ctx)
    avformat_close_input(&ctx->fmt_ctx);
  return ret;
}

/**
 * Safely releases, closes, and tears down all resources managed inside
 * the DemuxDecContext, preventing memory leaks between presentation runs.
 *
 * Deallocation operates in strict alignment with ownership rules:
 *   1. Destroys the software resampler context.
 *   2. Deallocates and closes the video and audio decoders.
 *   3. Closes the container format context and releases file descriptors.
 *   4. Frees dynamically allocated channel layout structures.
 *
 * @param ctx   Pointer to the active DemuxDecContext struct to clean up.
 */
void free_demux_dec_context(DemuxDecContext *ctx)
{
  if (!ctx)
    return;

  // Free the resampler context
  if (ctx->swr_ctx)
    swr_free(&ctx->swr_ctx);

  // Free the video decoder resources
  if (ctx->video_dec_ctx)
    avcodec_free_context(&ctx->video_dec_ctx);

  // Free the audio decoder resources
  if (ctx->audio_dec_ctx)
    avcodec_free_context(&ctx->audio_dec_ctx);

  // Close format input and set context back to NULL
  if (ctx->fmt_ctx)
    avformat_close_input(&ctx->fmt_ctx);

  // Uninitialize the custom target channel layout to prevent leaking layout maps
  av_channel_layout_uninit(&ctx->target_ch_layout);
}

/**
 * Custom I/O write callback for the AVIOContext.
 *
 * This function is triggered by the FFmpeg muxer whenever a chunk or fragment
 * of the fragmented MP4 (fMP4) stream is finalized in memory. It immediately
 * passes the pointer and size of the generated binary buffer back to the Go
 * runtime using the registered Go callback function and integer user token.
 *
 * @param opaque    A pointer to the user-defined TranscodeContext struct.
 * @param buf       The raw binary buffer containing fMP4 data.
 * @param buf_size  The size of the buffer in bytes.
 *
 * @return The number of written bytes, representing success or custom error.
 */
static int write_to_memory_cb(void *opaque, const uint8_t *buf, int buf_size)
{
  TranscodeContext *ctx = (TranscodeContext *)opaque;
  if (ctx && ctx->go_callback)
  {
    // Pass the integer token back to Go
    ctx->go_callback((uint8_t *)buf, buf_size, ctx->go_user_token);
  }
  return buf_size;
}

/**
 * Allocates and initializes the output Format Context specifically for
 * fragmented MP4 (fMP4) streaming without using any local filesystem disk I/O.
 *
 * This function handles allocating a custom, dynamic AVIOContext containing
 * a 4KB write-buffer. All data generated by the multiplexing phase is redirected
 * through our 'write_to_memory_cb' directly to Go.
 *
 * @param out_fmt_ctx  Pointer to the uninitialized AVFormatContext pointer.
 * @param tx_ctx       Pointer to the Go callback routing context structure.
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int init_fmp4_muxer(AVFormatContext **out_fmt_ctx, TranscodeContext *tx_ctx)
{
  int ret;
  size_t avio_buf_size = 4096;
  uint8_t *avio_buf = NULL;
  AVIOContext *avio_ctx = NULL;

  ret = avformat_alloc_output_context2(out_fmt_ctx, NULL, "mp4", NULL);
  if (ret < 0)
  {
    return ret;
  }

  avio_buf = (uint8_t *)av_malloc(avio_buf_size);
  if (!avio_buf)
  {
    avformat_free_context(*out_fmt_ctx);
    *out_fmt_ctx = NULL;
    return AVERROR(ENOMEM);
  }

  avio_ctx = avio_alloc_context(
      avio_buf,
      avio_buf_size,
      1,                  // Flag 1 sets the IO context to Write-Only mode
      tx_ctx,             // Passed into callbacks as 'opaque' parameter
      NULL,               // Read callback is unneeded for our live stream output
      write_to_memory_cb, // Primary write interceptor callback
      NULL                // Seek callback is omitted since we can't seek live TCP streams
  );

  if (!avio_ctx)
  {
    av_free(avio_buf);
    avformat_free_context(*out_fmt_ctx);
    *out_fmt_ctx = NULL;
    return AVERROR(ENOMEM);
  }

  (*out_fmt_ctx)->pb = avio_ctx;
  return 0;
}

/**
 * Formats and writes the initial fMP4 container headers to the memory context.
 *
 * This function injects the specific metadata options (`movflags`) required by
 * browser Media Source Extensions (MSE) to begin playback instantly.
 *
 * Options utilized:
 * - 'empty_moov': Writes a clean, frame-index-free structural header immediately.
 * - 'default_base_moof': Resolves frame offsets relative to fragment start points.
 * - 'frag_keyframe': Flushes a play-ready segment on every video keyframe.
 * - 'omit_tfhd_offset': Streamlines file metadata sizing for browser parsing.
 *
 * @param out_fmt_ctx  The output context allocated via init_fmp4_muxer.
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int write_fmp4_header(AVFormatContext *out_fmt_ctx)
{
  int ret;
  AVDictionary *opts = NULL;

  ret = av_dict_set(&opts, "movflags", "empty_moov+default_base_moof+frag_keyframe+omit_tfhd_offset", 0);
  if (ret < 0)
  {
    return ret;
  }

  ret = avformat_write_header(out_fmt_ctx, &opts);
  av_dict_free(&opts);
  return ret;
}

/**
 * Safely releases and tears down all allocations associated with the memory-based
 * fMP4 multiplexing context, completely eliminating memory leaks.
 *
 * It extracts the dynamic buffer inside the AVIOContext and frees it in the correct
 * chronological order to prevent dangling pointer faults.
 *
 * @param out_fmt_ctx  The output context to be deallocated.
 */
void free_fmp4_muxer(AVFormatContext *out_fmt_ctx)
{
  if (!out_fmt_ctx)
  {
    return;
  }

  if (out_fmt_ctx->pb)
  {
    // Free the internal dynamic 4KB buffer inside the AVIO structure
    av_freep(&out_fmt_ctx->pb->buffer);
    // Free the custom IO context structure
    avio_context_free(&out_fmt_ctx->pb);
  }

  avformat_free_context(out_fmt_ctx);
}

int get_miniaudio_devices(NativeAudioDevice *devices, int max_devices)
{
  ma_context context;
  if (ma_context_init(NULL, 0, NULL, &context) != MA_SUCCESS)
  {
    return -1;
  }

  ma_device_info *pPlaybackDeviceInfos;
  ma_uint32 playbackDeviceCount;
  if (ma_context_get_devices(&context, &pPlaybackDeviceInfos, &playbackDeviceCount, NULL, NULL) != MA_SUCCESS)
  {
    ma_context_uninit(&context);
    return -2;
  }

  int count = 0;

  for (ma_uint32 i = 0; i < playbackDeviceCount && count < max_devices; i++)
  {
    // Use the index 'i' (or a simplified name-based ID) to avoid ma_device_id struct issues
    snprintf(devices[count].id, sizeof(devices[count].id), "%u", i);

    // Use strncpy carefully; ensure 'devices' is a valid pointer
    strncpy(devices[count].name, pPlaybackDeviceInfos[i].name, sizeof(devices[count].name) - 1);

    // Ensure null-termination
    devices[count].name[sizeof(devices[count].name) - 1] = '\0';

    devices[count].is_default = pPlaybackDeviceInfos[i].isDefault;

    // Increment the count at the end of the loop
    count++;
  }

  ma_context_uninit(&context);
  return count;
}

int probe_media_properties(const char *file_path, CMediaProperties *props)
{
  if (!file_path || !props)
    return -1;

  // Zero out the target struct space safely
  memset(props, 0, sizeof(CMediaProperties));

  AVFormatContext *fmt_ctx = NULL;
  int ret = avformat_open_input(&fmt_ctx, file_path, NULL, NULL);
  if (ret < 0)
    return ret;

  ret = avformat_find_stream_info(fmt_ctx, NULL);
  if (ret < 0)
  {
    avformat_close_input(&fmt_ctx);
    return ret;
  }

  // 1. Populate Container Metadata
  if (fmt_ctx->iformat)
  {
    snprintf(props->format_name, sizeof(props->format_name), "%s", fmt_ctx->iformat->name ? fmt_ctx->iformat->name : "");
    snprintf(props->format_long_name, sizeof(props->format_long_name), "%s", fmt_ctx->iformat->long_name ? fmt_ctx->iformat->long_name : "");
  }
  if (fmt_ctx->duration != AV_NOPTS_VALUE)
  {
    props->duration_ms = (int64_t)(fmt_ctx->duration * 1000 / AV_TIME_BASE);
  }
  props->file_size_bytes = fmt_ctx->pb ? avio_size(fmt_ctx->pb) : 0;
  props->bit_rate = fmt_ctx->bit_rate;

  // 2. Extract Global Dict Tags Safely
  AVDictionaryEntry *tag = NULL;
  if ((tag = av_dict_get(fmt_ctx->metadata, "title", NULL, 0)))
    snprintf(props->title, sizeof(props->title), "%s", tag->value);
  if ((tag = av_dict_get(fmt_ctx->metadata, "artist", NULL, 0)))
    snprintf(props->author, sizeof(props->author), "%s", tag->value);
  else if ((tag = av_dict_get(fmt_ctx->metadata, "author", NULL, 0)))
    snprintf(props->author, sizeof(props->author), "%s", tag->value);
  if ((tag = av_dict_get(fmt_ctx->metadata, "album", NULL, 0)))
    snprintf(props->album, sizeof(props->album), "%s", tag->value);
  if ((tag = av_dict_get(fmt_ctx->metadata, "track", NULL, 0)))
    snprintf(props->track, sizeof(props->track), "%s", tag->value);
  if ((tag = av_dict_get(fmt_ctx->metadata, "genre", NULL, 0)))
    snprintf(props->genre, sizeof(props->genre), "%s", tag->value);
  if ((tag = av_dict_get(fmt_ctx->metadata, "creation_time", NULL, 0)))
    snprintf(props->creation_time, sizeof(props->creation_time), "%s", tag->value);

  // 3. Scan Across Stream Layout Arrays
  for (unsigned int i = 0; i < fmt_ctx->nb_streams; i++)
  {
    AVStream *stream = fmt_ctx->streams[i];
    AVCodecParameters *codec_par = stream->codecpar;

    // Handle Video Track
    if (codec_par->codec_type == AVMEDIA_TYPE_VIDEO && !props->has_video)
    {
      props->has_video = 1;
      props->width = codec_par->width;
      props->height = codec_par->height;

      const AVCodec *codec = avcodec_find_decoder(codec_par->codec_id);
      if (codec)
      {
        snprintf(props->video_codec, sizeof(props->video_codec), "%s", codec->name ? codec->name : "");
        snprintf(props->video_codec_long_name, sizeof(props->video_codec_long_name), "%s", codec->long_name ? codec->long_name : "");
      }

      // Framework Video Profile
      char profile_buf[64];
      avcodec_profile_name(codec_par->codec_id, codec_par->profile);
      snprintf(props->video_profile, sizeof(props->video_profile), "%s", avcodec_profile_name(codec_par->codec_id, codec_par->profile) ? avcodec_profile_name(codec_par->codec_id, codec_par->profile) : "Unknown");

      // Frame rate parsing
      AVRational frame_rate = av_guess_frame_rate(fmt_ctx, stream, NULL);
      if (frame_rate.den > 0)
      {
        props->framerate = av_q2d(frame_rate);
      }

      // Aspect Ratio tracking
      AVRational dar;
      av_reduce(&dar.num, &dar.den, codec_par->width * stream->sample_aspect_ratio.num, codec_par->height * stream->sample_aspect_ratio.den, 1024 * 1024);
      if (dar.num > 0 && dar.den > 0)
      {
        snprintf(props->aspect_ratio, sizeof(props->aspect_ratio), "%d:%d", dar.num, dar.den);
      }

      // Pixel specs and Color Spaces
      const char *pix_fmt_name = av_get_pix_fmt_name(codec_par->format);
      snprintf(props->pixel_format, sizeof(props->pixel_format), "%s", pix_fmt_name ? pix_fmt_name : "");
      snprintf(props->color_space, sizeof(props->color_space), "%s", av_color_space_name(codec_par->color_space) ? av_color_space_name(codec_par->color_space) : "");
      snprintf(props->color_transfer, sizeof(props->color_transfer), "%s", av_color_transfer_name(codec_par->color_trc) ? av_color_transfer_name(codec_par->color_trc) : "");
      snprintf(props->color_primaries, sizeof(props->color_primaries), "%s", av_color_primaries_name(codec_par->color_primaries) ? av_color_primaries_name(codec_par->color_primaries) : "");
    }

    // Handle Audio Track
    else if (codec_par->codec_type == AVMEDIA_TYPE_AUDIO && !props->has_audio)
    {
      props->has_audio = 1;
      props->audio_channels = codec_par->ch_layout.nb_channels;
      props->sample_rate = codec_par->sample_rate;
      props->audio_bit_rate = codec_par->bit_rate;

      const AVCodec *codec = avcodec_find_decoder(codec_par->codec_id);
      if (codec)
      {
        snprintf(props->audio_codec, sizeof(props->audio_codec), "%s", codec->name ? codec->name : "");
        snprintf(props->audio_codec_long_name, sizeof(props->audio_codec_long_name), "%s", codec->long_name ? codec->long_name : "");
      }

      snprintf(props->audio_profile, sizeof(props->audio_profile), "%s", avcodec_profile_name(codec_par->codec_id, codec_par->profile) ? avcodec_profile_name(codec_par->codec_id, codec_par->profile) : "Unknown");

      // Unpack Channel layout descriptive labels natively
      char layout_buf[64];
      av_channel_layout_describe(&codec_par->ch_layout, layout_buf, sizeof(layout_buf));
      snprintf(props->channel_layout, sizeof(props->channel_layout), "%s", layout_buf);
    }
  }

  // Context demolition cleanup
  avformat_close_input(&fmt_ctx);
  return 0;
}

int extract_video_screenshot(const char *file_path, int64_t time_ms, uint8_t **out_buf, int *out_size)
{
  if (!file_path || !out_buf || !out_size)
    return -1;
  *out_buf = NULL;
  *out_size = 0;

  AVFormatContext *fmt_ctx = NULL;
  if (avformat_open_input(&fmt_ctx, file_path, NULL, NULL) < 0)
    return -1;
  if (avformat_find_stream_info(fmt_ctx, NULL) < 0)
  {
    avformat_close_input(&fmt_ctx);
    return -1;
  }

  // 1. Locate primary video track
  int video_stream_idx = -1;
  for (unsigned int i = 0; i < fmt_ctx->nb_streams; i++)
  {
    if (fmt_ctx->streams[i]->codecpar->codec_type == AVMEDIA_TYPE_VIDEO)
    {
      video_stream_idx = i;
      break;
    }
  }

  if (video_stream_idx == -1)
  {
    avformat_close_input(&fmt_ctx);
    return -2; // No video stream found
  }

  AVStream *stream = fmt_ctx->streams[video_stream_idx];
  AVCodecParameters *codec_par = stream->codecpar;

  // 2. Initialize input decoder context
  const AVCodec *decoder = avcodec_find_decoder(codec_par->codec_id);
  if (!decoder)
  {
    avformat_close_input(&fmt_ctx);
    return -3;
  }
  AVCodecContext *dec_ctx = avcodec_alloc_context3(decoder);
  avcodec_parameters_to_context(dec_ctx, codec_par);
  if (avcodec_open2(dec_ctx, decoder, NULL) < 0)
  {
    avcodec_free_context(&dec_ctx);
    avformat_close_input(&fmt_ctx);
    return -4;
  }

  // 3. Compute stream specific seek timestamp bounds
  // Convert ms to stream time base units: units = (ms / 1000) / time_base
  int64_t seek_target = (int64_t)(time_ms * (int64_t)AV_TIME_BASE / 1000);
  seek_target = av_rescale_q(seek_target, AV_TIME_BASE_Q, stream->time_base);

  // Seek to the closest keyframe before or at the requested timeline point
  if (avformat_seek_file(fmt_ctx, video_stream_idx, INT64_MIN, seek_target, seek_target, AVSEEK_FLAG_BACKWARD) < 0)
  {
    avcodec_free_context(&dec_ctx);
    avformat_close_input(&fmt_ctx);
    return -5;
  }

  // Flush decoder state variables after a seek event
  avcodec_flush_buffers(dec_ctx);

  AVPacket *pkt = av_packet_alloc();
  AVFrame *frame = av_frame_alloc();
  int frame_decoded = 0;

  // 4. Extraction decoding pump loop
  while (av_read_frame(fmt_ctx, pkt) >= 0)
  {
    if (pkt->stream_index == video_stream_idx)
    {
      if (avcodec_send_packet(dec_ctx, pkt) >= 0)
      {
        if (avcodec_receive_frame(dec_ctx, frame) >= 0)
        {
          frame_decoded = 1;
          av_packet_unref(pkt);
          break;
        }
      }
    }
    av_packet_unref(pkt);
  }
  av_packet_free(&pkt);

  if (!frame_decoded)
  {
    av_frame_free(&frame);
    avcodec_free_context(&dec_ctx);
    avformat_close_input(&fmt_ctx);
    return -6; // Failed to decode a usable frame
  }

  // 5. Setup internal MJPEG image encoder pipeline
  const AVCodec *encoder = avcodec_find_encoder(AV_CODEC_ID_MJPEG);
  if (!encoder)
  {
    av_frame_free(&frame);
    avcodec_free_context(&dec_ctx);
    avformat_close_input(&fmt_ctx);
    return -7;
  }

  AVCodecContext *enc_ctx = avcodec_alloc_context3(encoder);
  enc_ctx->width = dec_ctx->width;
  enc_ctx->height = dec_ctx->height;
  // Set format matching standard MJPEG requirements (YUVJ420P or YUV420P depending on compilation)
  enc_ctx->pix_fmt = AV_PIX_FMT_YUVJ420P;
  enc_ctx->time_base = (AVRational){1, 25};

  if (avcodec_open2(enc_ctx, encoder, NULL) < 0)
  {
    av_frame_free(&frame);
    enc_ctx->pix_fmt = AV_PIX_FMT_YUV420P; // Try fallback if YUVJ420P is constrained
    if (avcodec_open2(enc_ctx, encoder, NULL) < 0)
    {
      avcodec_free_context(&enc_ctx);
      av_frame_free(&frame);
      avcodec_free_context(&dec_ctx);
      avformat_close_input(&fmt_ctx);
      return -8;
    }
  }

  // Ensure our frame format matches encoder expectations or enforce color ranges
  frame->format = enc_ctx->pix_fmt;

  AVPacket *enc_pkt = av_packet_alloc();
  int encode_success = 0;

  if (avcodec_send_frame(enc_ctx, frame) >= 0)
  {
    if (avcodec_receive_packet(enc_ctx, enc_pkt) >= 0)
    {
      // Allocate memory boundary directly on the C heap to hold raw binary data safely
      *out_buf = (uint8_t *)av_malloc(enc_pkt->size);
      if (*out_buf)
      {
        memcpy(*out_buf, enc_pkt->data, enc_pkt->size);
        *out_size = enc_pkt->size;
        encode_success = 1;
      }
    }
  }

  // Final multi-context teardown and cleanup routines
  av_packet_free(&enc_pkt);
  av_frame_free(&frame);
  avcodec_free_context(&enc_ctx);
  avcodec_free_context(&dec_ctx);
  avformat_close_input(&fmt_ctx);

  return encode_success ? 0 : -9;
}

/**
 * Seeks to a specific time in milliseconds.
 * Flushes decoders and seeks the format context.
 * Note: This is a basic implementation. Full seamless seeking while streaming
 * fMP4 to MSE requires additional frontend handling.
 */
int seek_playback(DemuxDecContext *dec_ctx, int64_t seek_time_ms)
{
  if (!dec_ctx || !dec_ctx->fmt_ctx)
  {
    return -1;
  }

  int64_t seek_target = (int64_t)(seek_time_ms * (int64_t)AV_TIME_BASE / 1000);

  // Seek on video stream if available, otherwise on default
  int stream_index = dec_ctx->video_stream_idx >= 0 ? dec_ctx->video_stream_idx : -1;

  int ret = av_seek_frame(dec_ctx->fmt_ctx, stream_index, seek_target, AVSEEK_FLAG_BACKWARD);
  if (ret < 0)
  {
    return ret;
  }

  // Flush decoders
  if (dec_ctx->video_dec_ctx)
  {
    avcodec_flush_buffers(dec_ctx->video_dec_ctx);
  }
  if (dec_ctx->audio_dec_ctx)
  {
    avcodec_flush_buffers(dec_ctx->audio_dec_ctx);
  }

  return 0;
}

int run_streaming_mux_and_play(DemuxDecContext *dec_ctx, uintptr_t go_token)
{
  int ret;
  TranscodeContext tx_ctx;
  AVFormatContext *out_fmt_ctx = NULL;
  AVPacket *pkt = NULL;
  AVFrame *frame = NULL;

  tx_ctx.go_user_token = go_token;
  tx_ctx.go_callback = goTestWriteCallback;

  // Initialize in-memory fMP4 muxer
  ret = init_fmp4_muxer(&out_fmt_ctx, &tx_ctx);
  if (ret < 0)
    return ret;

  // 1. Mux Video Stream
  //    - Passthrough when the source is already H.264 (zero CPU / zero quality loss)
  //    - Otherwise force a highly compatible H.264 re-encode so every file plays in
  //      Chrome / Edge / Safari MSE.
  int out_video_idx = -1;
  bool need_video_reencode = false;
  AVCodecContext *h264_enc_ctx = NULL;
  struct SwsContext *sws_ctx = NULL;
  AVFrame *enc_video_frame = NULL;
  AVPacket *enc_video_pkt = NULL;

  if (dec_ctx->video_stream_idx >= 0 && dec_ctx->video_dec_ctx)
  {
    need_video_reencode = (dec_ctx->video_dec_ctx->codec_id != AV_CODEC_ID_H264);

    if (!need_video_reencode)
    {
      // Fast path – pure passthrough
      AVStream *in_stream = dec_ctx->fmt_ctx->streams[dec_ctx->video_stream_idx];
      AVStream *out_stream = avformat_new_stream(out_fmt_ctx, NULL);
      if (!out_stream)
      {
        free_fmp4_muxer(out_fmt_ctx);
        return AVERROR(ENOMEM);
      }
      ret = avcodec_parameters_copy(out_stream->codecpar, in_stream->codecpar);
      if (ret < 0)
      {
        free_fmp4_muxer(out_fmt_ctx);
        return ret;
      }
      out_stream->codecpar->codec_tag = 0;
      out_video_idx = out_stream->index;
    }
    else
    {
      // Slow path – force H.264 (Baseline/Main, low-latency, GLOBAL_HEADER)
      const AVCodec *h264_codec = avcodec_find_encoder(AV_CODEC_ID_H264);
      if (!h264_codec)
      {
        free_fmp4_muxer(out_fmt_ctx);
        return AVERROR_ENCODER_NOT_FOUND;
      }

      h264_enc_ctx = avcodec_alloc_context3(h264_codec);
      if (!h264_enc_ctx)
      {
        free_fmp4_muxer(out_fmt_ctx);
        return AVERROR(ENOMEM);
      }

      h264_enc_ctx->width = dec_ctx->video_dec_ctx->width;
      h264_enc_ctx->height = dec_ctx->video_dec_ctx->height;
      h264_enc_ctx->pix_fmt = AV_PIX_FMT_YUV420P;
      h264_enc_ctx->time_base = (AVRational){1, 90000};
      h264_enc_ctx->framerate = av_guess_frame_rate(
          dec_ctx->fmt_ctx,
          dec_ctx->fmt_ctx->streams[dec_ctx->video_stream_idx],
          NULL);
      if (h264_enc_ctx->framerate.num == 0)
        h264_enc_ctx->framerate = (AVRational){25, 1};

      h264_enc_ctx->gop_size = 48;
      h264_enc_ctx->max_b_frames = 0; // better for frag_keyframe + low latency
      h264_enc_ctx->bit_rate = 2500000;
      h264_enc_ctx->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;

      av_opt_set(h264_enc_ctx->priv_data, "profile", "main", 0);
      av_opt_set(h264_enc_ctx->priv_data, "preset", "veryfast", 0);
      av_opt_set(h264_enc_ctx->priv_data, "tune", "zerolatency", 0);

      if (avcodec_open2(h264_enc_ctx, h264_codec, NULL) < 0)
      {
        avcodec_free_context(&h264_enc_ctx);
        free_fmp4_muxer(out_fmt_ctx);
        return AVERROR_UNKNOWN;
      }

      AVStream *out_stream = avformat_new_stream(out_fmt_ctx, NULL);
      if (!out_stream)
      {
        avcodec_free_context(&h264_enc_ctx);
        free_fmp4_muxer(out_fmt_ctx);
        return AVERROR(ENOMEM);
      }
      avcodec_parameters_from_context(out_stream->codecpar, h264_enc_ctx);
      out_stream->codecpar->codec_tag = 0;
      out_video_idx = out_stream->index;

      // Colour-space converter (any decoder output -> YUV420P)
      sws_ctx = sws_getContext(
          dec_ctx->video_dec_ctx->width, dec_ctx->video_dec_ctx->height,
          dec_ctx->video_dec_ctx->pix_fmt,
          h264_enc_ctx->width, h264_enc_ctx->height, AV_PIX_FMT_YUV420P,
          SWS_BILINEAR, NULL, NULL, NULL);

      enc_video_frame = av_frame_alloc();
      enc_video_frame->format = AV_PIX_FMT_YUV420P;
      enc_video_frame->width = h264_enc_ctx->width;
      enc_video_frame->height = h264_enc_ctx->height;
      av_frame_get_buffer(enc_video_frame, 32);

      enc_video_pkt = av_packet_alloc();
    }
  }

  // 2. Setup AAC Audio Transcoder & Mux Stream
  int out_audio_idx = -1;
  AVCodecContext *aac_enc_ctx = NULL;
  AVAudioFifo *fifo = NULL;
  AVFrame *enc_frame = NULL;
  AVPacket *enc_pkt = NULL;
  uint8_t *resample_buf[2] = {NULL, NULL};
  int64_t audio_pts_counter = -1; // Allows clean reset after seek

  if (dec_ctx->audio_stream_idx >= 0)
  {
    const AVCodec *aac_codec = avcodec_find_encoder(AV_CODEC_ID_AAC);
    if (aac_codec)
    {
      aac_enc_ctx = avcodec_alloc_context3(aac_codec);
      aac_enc_ctx->sample_rate = 48000;
      av_channel_layout_default(&aac_enc_ctx->ch_layout, 2);
      aac_enc_ctx->sample_fmt = AV_SAMPLE_FMT_FLTP;
      aac_enc_ctx->bit_rate = 192000;
      aac_enc_ctx->time_base = (AVRational){1, 48000};   // Required for smooth MSE sync
      aac_enc_ctx->flags |= AV_CODEC_FLAG_GLOBAL_HEADER; // Essential for MSE AAC extradata

      if (avcodec_open2(aac_enc_ctx, aac_codec, NULL) >= 0)
      {
        AVStream *out_stream = avformat_new_stream(out_fmt_ctx, NULL);
        out_audio_idx = out_stream->index;
        avcodec_parameters_from_context(out_stream->codecpar, aac_enc_ctx);
        out_stream->codecpar->codec_tag = 0;

        // FFmpeg AAC strict frame size enforcement (1024 frames)
        fifo = av_audio_fifo_alloc(aac_enc_ctx->sample_fmt, 2, 32768);
        enc_frame = av_frame_alloc();
        enc_frame->nb_samples = aac_enc_ctx->frame_size;
        enc_frame->format = aac_enc_ctx->sample_fmt;
        av_channel_layout_copy(&enc_frame->ch_layout, &aac_enc_ctx->ch_layout);
        av_frame_get_buffer(enc_frame, 0);
        enc_pkt = av_packet_alloc();

        // Static buffer for intermediate SWR conversions (up to 8192 samples per read)
        av_samples_alloc(resample_buf, NULL, 2, 8192, AV_SAMPLE_FMT_FLTP, 0);
      }
    }
  }

  ret = write_fmp4_header(out_fmt_ctx);
  if (ret < 0)
    goto cleanup; // Ensures any audio resources allocated above are freed

  pkt = av_packet_alloc();
  frame = av_frame_alloc();
  if (!pkt || !frame)
  {
    ret = AVERROR(ENOMEM);
    goto cleanup;
  }

  // CRITICAL: Real-time pacing variables.
  // Track the exact microsecond the stream starts + accumulated pause time so we
  // never deliver more than READ_AHEAD_US (10 s) of future media.
  int64_t stream_start_time_us = av_gettime_relative();
  int64_t total_pause_us = 0;
  int64_t current_pause_start_us = 0;
  const int64_t READ_AHEAD_US = 10000000LL; // 10 seconds of runway
  int just_seeked = 0;

  // Main streaming loop — designed to stay alive and react to control signals.
  while (true)
  {
    // Check control flags from Go side (Option 3 style)
    // Atomic loads for thread-safety. The Go control thread (ControlStream)
    // can set these flags at any time without locking the entire pipeline.
    if (__atomic_load_n(&dec_ctx->stop_requested, __ATOMIC_ACQUIRE))
      break;

    if (__atomic_load_n(&dec_ctx->seek_requested, __ATOMIC_ACQUIRE))
    {
      int64_t target_ms = __atomic_load_n(&dec_ctx->seek_target_ms, __ATOMIC_ACQUIRE);
      // Perform seek on the format context + flush decoders.
      // Safe because we do it from inside the read-loop thread,
      // avoiding race conditions with av_read_frame.
      int64_t seek_target = (int64_t)(target_ms * (int64_t)AV_TIME_BASE / 1000);
      int stream_idx = dec_ctx->video_stream_idx >= 0 ? dec_ctx->video_stream_idx : -1;

      if (av_seek_frame(dec_ctx->fmt_ctx, stream_idx, seek_target, AVSEEK_FLAG_BACKWARD) >= 0)
      {
        // Flush video decoders/encoders
        if (dec_ctx->video_dec_ctx)
          avcodec_flush_buffers(dec_ctx->video_dec_ctx);
        // H.264 encoder can be flushed
        if (h264_enc_ctx)
        {
          avcodec_flush_buffers(h264_enc_ctx);
          // Force the next video frame to be a keyframe
          h264_enc_ctx->frame_num = 0; // helps some encoders
        }

        // Flush Audio decoders and FIFO
        if (dec_ctx->audio_dec_ctx)
          avcodec_flush_buffers(dec_ctx->audio_dec_ctx);
        if (fifo)
          av_audio_fifo_reset(fifo);

        // CRITICAL FIX: Recreate the AAC Encoder
        // Native AAC encoder does not reset its internal PTS tracker on flush.
        // We must destroy and recreate it to prevent "Queue input is backward in time"
        // and fatal DTS monotonicity errors inside the newly spawned muxer.
        if (aac_enc_ctx)
        {
          avcodec_free_context(&aac_enc_ctx);

          const AVCodec *aac_codec = avcodec_find_encoder(AV_CODEC_ID_AAC);
          aac_enc_ctx = avcodec_alloc_context3(aac_codec);
          aac_enc_ctx->sample_rate = 48000;
          av_channel_layout_default(&aac_enc_ctx->ch_layout, 2);
          aac_enc_ctx->sample_fmt = AV_SAMPLE_FMT_FLTP;
          aac_enc_ctx->bit_rate = 192000;
          aac_enc_ctx->time_base = (AVRational){1, 48000};
          aac_enc_ctx->flags |= AV_CODEC_FLAG_GLOBAL_HEADER;

          avcodec_open2(aac_enc_ctx, aac_codec, NULL);

          // Reset audio PTS exactly to the target time
          audio_pts_counter = (target_ms * 48000LL) / 1000; // samples at 48 kHz
        }

        // CRITICAL FIX: Recreate the fMP4 Muxer Context
        // This wipes the internal DTS trackers, preventing the "non monotonically increasing" crash.
        // It outputs a fresh `moov` header to the browser, safely resetting the MSE engine timeline.
        if (out_fmt_ctx)
        {
          free_fmp4_muxer(out_fmt_ctx);
          out_fmt_ctx = NULL;
        }

        init_fmp4_muxer(&out_fmt_ctx, &tx_ctx);

        // Re-map the video stream into the new muxer
        if (dec_ctx->video_stream_idx >= 0)
        {
          AVStream *out_stream = avformat_new_stream(out_fmt_ctx, NULL);
          if (!need_video_reencode)
          {
            avcodec_parameters_copy(out_stream->codecpar, dec_ctx->fmt_ctx->streams[dec_ctx->video_stream_idx]->codecpar);
          }
          else if (h264_enc_ctx)
          {
            avcodec_parameters_from_context(out_stream->codecpar, h264_enc_ctx);
          }
          out_stream->codecpar->codec_tag = 0;
          out_video_idx = out_stream->index;
        }

        // Re-map the audio stream into the new muxer
        if (dec_ctx->audio_stream_idx >= 0 && aac_enc_ctx)
        {
          AVStream *out_stream = avformat_new_stream(out_fmt_ctx, NULL);
          avcodec_parameters_from_context(out_stream->codecpar, aac_enc_ctx);
          out_stream->codecpar->codec_tag = 0;
          out_audio_idx = out_stream->index;
        }

        // Write the new initialization segment downstream
        write_fmp4_header(out_fmt_ctx);

        // CRITICAL: Reset wall-clock baseline so the throttle aligns with the new seek position
        stream_start_time_us = av_gettime_relative() - (target_ms * 1000LL);
        total_pause_us = 0;
        current_pause_start_us = 0;
        just_seeked = 1;

        printf("[C-SEEK] Seek to %lld ms succeeded. Resetting PTS counters.\n", (long long)target_ms);
        fflush(stdout);
      }

      // Clear the lock flag so the loop proceeds
      __atomic_store_n(&dec_ctx->seek_requested, 0, __ATOMIC_RELEASE);
      continue;
    }

    if (__atomic_load_n(&dec_ctx->paused, __ATOMIC_ACQUIRE))
    {
      // Track exactly how long we are paused so we don't burst data when resumed
      if (current_pause_start_us == 0)
        current_pause_start_us = av_gettime_relative();
      av_usleep(20000);
      continue;
    }
    else if (current_pause_start_us > 0)
    {
      // Add the duration of the pause to our total offset and reset
      total_pause_us += (av_gettime_relative() - current_pause_start_us);
      current_pause_start_us = 0;
    }

    ret = av_read_frame(dec_ctx->fmt_ctx, pkt);
    if (ret == AVERROR_EOF || ret < 0)
      break;

    if (ret >= 0)
    {
      printf("[C-READ] stream=%d  pts=%lld\n", pkt->stream_index, (long long)pkt->pts);
      fflush(stdout);
    }

    // VIDEO PATH
    if (pkt->stream_index == dec_ctx->video_stream_idx && out_video_idx >= 0)
    {
      if (!need_video_reencode)
      {
        // Passthrough (original path)
        AVStream *in_stream = dec_ctx->fmt_ctx->streams[dec_ctx->video_stream_idx];
        AVStream *out_stream = out_fmt_ctx->streams[out_video_idx];

        double calculated_pts = pkt->pts != AV_NOPTS_VALUE
                                    ? pkt->pts * av_q2d(in_stream->time_base)
                                    : 0.0;
        int64_t pkt_time_us = (int64_t)(calculated_pts * 1000000.0);

        extern void set_session_pts(uintptr_t token, double pts);
        set_session_pts(tx_ctx.go_user_token, calculated_pts);

        // CRITICAL: Real-time pacing lock.
        // Forces the C pipeline to sleep if it is generating data faster than
        // the real-world clock (plus our 10-second buffer allowance).
        // Also aborts the wait immediately on any control signal.
        int interrupted = 0;

        if (just_seeked)
        {
          // Force a keyframe on the first frame after a seek:
          frame->pict_type = AV_PICTURE_TYPE_I;

          // First packet after a seek -> force the clock to match reality
          // so we don't sleep for minutes
          stream_start_time_us = av_gettime_relative() - pkt_time_us;
          just_seeked = 0;
        }
        else
        {
          while (true)
          {
            if (__atomic_load_n(&dec_ctx->stop_requested, __ATOMIC_ACQUIRE) ||
                __atomic_load_n(&dec_ctx->seek_requested, __ATOMIC_ACQUIRE) ||
                __atomic_load_n(&dec_ctx->paused, __ATOMIC_ACQUIRE))
            {
              interrupted = 1;
              break;
            }

            int64_t elapsed_us = av_gettime_relative() - stream_start_time_us - total_pause_us;
            if (pkt_time_us > elapsed_us + READ_AHEAD_US)
              av_usleep(15000); // Sleep 15 ms and re-evaluate the clock
            else
              break; // Clock has caught up – proceed with remuxing
          }
        }

        // Only write if the throttle was not interrupted by a control signal.
        // (Writing an outdated packet after a seek would corrupt the timeline.)
        if (!interrupted)
        {
          av_packet_rescale_ts(pkt, in_stream->time_base, out_stream->time_base);
          pkt->stream_index = out_video_idx;

          // Catch fatal container formatting errors instead of feeding garbage to the browser
          printf("[C-MUX] Writing %s packet pts=%lld  size=%d\n",
                 (pkt->stream_index == out_video_idx) ? "VIDEO" : "AUDIO",
                 (long long)(enc_video_pkt ? enc_video_pkt->pts : pkt->pts),
                 enc_video_pkt ? enc_video_pkt->size : pkt->size);
          fflush(stdout);
          if (av_interleaved_write_frame(out_fmt_ctx, pkt) < 0)
            __atomic_store_n(&dec_ctx->stop_requested, 1, __ATOMIC_RELEASE);
        }
      }
      else
      {
        // Full H.264 re-encode path (with real-time pacing)
        if (avcodec_send_packet(dec_ctx->video_dec_ctx, pkt) >= 0)
        {
          while (avcodec_receive_frame(dec_ctx->video_dec_ctx, frame) >= 0)
          {
            // Convert PTS from the input stream time_base -> encoder time_base
            AVStream *in_stream = dec_ctx->fmt_ctx->streams[dec_ctx->video_stream_idx];
            enc_video_frame->pts = av_rescale_q(frame->pts,
                                                in_stream->time_base,
                                                h264_enc_ctx->time_base);

            // Real-time pacing (identical logic to the passthrough path)
            double calculated_pts = frame->pts != AV_NOPTS_VALUE
                                        ? frame->pts * av_q2d(in_stream->time_base)
                                        : 0.0;
            int64_t pkt_time_us = (int64_t)(calculated_pts * 1000000.0);

            extern void set_session_pts(uintptr_t token, double pts);
            set_session_pts(tx_ctx.go_user_token, calculated_pts);

            int interrupted = 0;

            if (just_seeked)
            {
              // Force a keyframe on the first frame after a seek:
              frame->pict_type = AV_PICTURE_TYPE_I;

              // First packet after a seek -> force the clock to match reality
              // so we don't sleep for minutes
              stream_start_time_us = av_gettime_relative() - pkt_time_us;
              just_seeked = 0;
            }
            else
            {
              while (true)
              {
                if (__atomic_load_n(&dec_ctx->stop_requested, __ATOMIC_ACQUIRE) ||
                    __atomic_load_n(&dec_ctx->seek_requested, __ATOMIC_ACQUIRE) ||
                    __atomic_load_n(&dec_ctx->paused, __ATOMIC_ACQUIRE))
                {
                  interrupted = 1;
                  break;
                }

                int64_t elapsed_us = av_gettime_relative() - stream_start_time_us - total_pause_us;
                if (pkt_time_us > elapsed_us + READ_AHEAD_US)
                  av_usleep(15000);
                else
                  break;
              }
            }

            if (interrupted)
              continue; // drop this frame, control signal will be handled on next loop

            // Colour conversion + encode
            sws_scale(sws_ctx,
                      (const uint8_t *const *)frame->data, frame->linesize,
                      0, frame->height,
                      enc_video_frame->data, enc_video_frame->linesize);

            if (avcodec_send_frame(h264_enc_ctx, enc_video_frame) >= 0)
            {
              while (avcodec_receive_packet(h264_enc_ctx, enc_video_pkt) >= 0)
              {
                av_packet_rescale_ts(enc_video_pkt,
                                     h264_enc_ctx->time_base,
                                     out_fmt_ctx->streams[out_video_idx]->time_base);
                enc_video_pkt->stream_index = out_video_idx;

                printf("[C-MUX] Writing %s packet pts=%lld  size=%d\n",
                       (pkt->stream_index == out_video_idx) ? "VIDEO" : "AUDIO",
                       (long long)(enc_video_pkt ? enc_video_pkt->pts : pkt->pts),
                       enc_video_pkt ? enc_video_pkt->size : pkt->size);
                fflush(stdout);
                if (av_interleaved_write_frame(out_fmt_ctx, enc_video_pkt) < 0)
                  __atomic_store_n(&dec_ctx->stop_requested, 1, __ATOMIC_RELEASE);

                av_packet_unref(enc_video_pkt);
              }
            }
          }
        }
      }
    }

    // AUDIO PATH
    else if (pkt->stream_index == dec_ctx->audio_stream_idx && aac_enc_ctx && fifo)
    {
      if (avcodec_send_packet(dec_ctx->audio_dec_ctx, pkt) >= 0)
      {
        while (avcodec_receive_frame(dec_ctx->audio_dec_ctx, frame) >= 0)
        {
          // Convert to FLTP 48 kHz Stereo
          int out_samples = swr_convert(dec_ctx->swr_ctx, resample_buf, 8192,
                                        (const uint8_t **)frame->data, frame->nb_samples);
          if (out_samples > 0)
          {
            // CRITICAL: Dynamically reallocate the FIFO BEFORE writing.
            // Without this, av_audio_fifo_write silently drops samples once the
            // fixed 8192-sample buffer fills. Dropped samples produce A/V desync
            // that surfaces as MEDIA_ERR_DECODE (Code 3) in the browser.
            int realloc_ret = av_audio_fifo_realloc(fifo, av_audio_fifo_size(fifo) + out_samples);
            if (realloc_ret < 0)
            {
              char err_str[AV_ERROR_MAX_STRING_SIZE];
              av_make_error_string(err_str, AV_ERROR_MAX_STRING_SIZE, realloc_ret);
              av_log(NULL, AV_LOG_ERROR, "Could not reallocate audio FIFO: %s\n", err_str);

              // Treat as fatal – stop the whole streaming loop cleanly
              __atomic_store_n(&dec_ctx->stop_requested, 1, __ATOMIC_RELEASE);
              goto cleanup;
            }
            av_audio_fifo_write(fifo, (void **)resample_buf, out_samples);
          }

          // Consume from FIFO to feed AAC Encoder (needs exactly frame_size per packet)
          while (av_audio_fifo_size(fifo) >= aac_enc_ctx->frame_size)
          {
            av_audio_fifo_read(fifo, (void **)enc_frame->data, aac_enc_ctx->frame_size);
            if (audio_pts_counter == -1)
              audio_pts_counter = 0;
            enc_frame->pts = audio_pts_counter;
            audio_pts_counter += aac_enc_ctx->frame_size;

            if (avcodec_send_frame(aac_enc_ctx, enc_frame) >= 0)
            {
              while (avcodec_receive_packet(aac_enc_ctx, enc_pkt) >= 0)
              {
                av_packet_rescale_ts(enc_pkt, aac_enc_ctx->time_base,
                                     out_fmt_ctx->streams[out_audio_idx]->time_base);
                enc_pkt->stream_index = out_audio_idx;

                // Native FFmpeg function safely interleaves the binary audio and video data
                // printf("[C-MUX] Writing %s packet pts=%lld  size=%d\n",
                //        (pkt->stream_index == out_video_idx || /* re-encode case */) ? "VIDEO" : "AUDIO",
                //        (long long)(enc_video_pkt ? enc_video_pkt->pts : pkt->pts),
                //        enc_video_pkt ? enc_video_pkt->size : pkt->size);
                // fflush(stdout);
                if (av_interleaved_write_frame(out_fmt_ctx, enc_pkt) < 0)
                  __atomic_store_n(&dec_ctx->stop_requested, 1, __ATOMIC_RELEASE);
                av_packet_unref(enc_pkt);
              }
            }
          }
        }
      }
    }
    av_packet_unref(pkt);
  }

  // Flush H.264 encoder on EOF (only when we actually re-encoded)
  if (need_video_reencode && h264_enc_ctx)
  {
    avcodec_send_frame(h264_enc_ctx, NULL); // return value intentionally ignored on flush
    while (avcodec_receive_packet(h264_enc_ctx, enc_video_pkt) >= 0)
    {
      av_packet_rescale_ts(enc_video_pkt,
                           h264_enc_ctx->time_base,
                           out_fmt_ctx->streams[out_video_idx]->time_base);
      enc_video_pkt->stream_index = out_video_idx;
      av_interleaved_write_frame(out_fmt_ctx, enc_video_pkt);
      av_packet_unref(enc_video_pkt);
    }
  }

  // Write trailer to finalize the last fMP4 fragment
  if (out_fmt_ctx)
    av_write_trailer(out_fmt_ctx);

cleanup:
  if (frame)
    av_frame_free(&frame);
  if (pkt)
    av_packet_free(&pkt);
  if (enc_frame)
    av_frame_free(&enc_frame);
  if (enc_pkt)
    av_packet_free(&enc_pkt);
  if (enc_video_frame)
    av_frame_free(&enc_video_frame);
  if (enc_video_pkt)
    av_packet_free(&enc_video_pkt);
  if (fifo)
    av_audio_fifo_free(fifo);
  if (resample_buf[0])
    av_freep(&resample_buf[0]); // Frees the contiguous memory block
  if (sws_ctx)
    sws_freeContext(sws_ctx);
  if (h264_enc_ctx)
    avcodec_free_context(&h264_enc_ctx);
  if (aac_enc_ctx)
    avcodec_free_context(&aac_enc_ctx);
  if (out_fmt_ctx)
    free_fmp4_muxer(out_fmt_ctx);

  return ret;
}

// Small helpers to set control flags from Go in a clean way
void set_dec_ctx_paused(DemuxDecContext *ctx, int paused)
{
  if (ctx)
  {
    __atomic_store_n(&ctx->paused, paused, __ATOMIC_RELEASE);
  }
}

void request_seek_on_dec_ctx(DemuxDecContext *ctx, int64_t seek_ms)
{
  if (ctx)
  {
    __atomic_store_n(&ctx->seek_target_ms, seek_ms, __ATOMIC_RELEASE);
    __atomic_store_n(&ctx->seek_requested, 1, __ATOMIC_RELEASE);
  }
}

void request_stop_on_dec_ctx(DemuxDecContext *ctx)
{
  if (ctx)
  {
    __atomic_store_n(&ctx->stop_requested, 1, __ATOMIC_RELEASE);
  }
}