#define MA_NO_VERSIONING
#define MINIAUDIO_IMPLEMENTATION
#include "decoder.h"
#include <libavutil/opt.h>
#include <libavutil/channel_layout.h>
#include <string.h>
// Include the autogenerated header
#include "_cgo_export.h"

/**
 * Initializes the audio resampler context (SwrContext).
 *
 * Media files contain various sample rates (e.g., 44.1kHz, 48kHz), formats (e.g., s16, s32, flt),
 * and channel layouts (e.g., Mono, Stereo, 5.1). Miniaudio requires a consistent and predictable
 * hardware format to route audio cleanly.
 *
 * This function standardizes any incoming audio stream to:
 *   - Sample Rate: 48,000 Hz (48kHz Studio Quality)
 *   - Channels: 2 Channels (Stereo)
 *   - Format: 32-bit Floating Point (highly compatible with miniaudio & modern sound cards)
 *
 * @param ctx   Pointer to the active DemuxDecContext tracking the audio decoder.
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int init_audio_resampler(DemuxDecContext *ctx)
{
  int ret;

  // Set normalized audio properties
  ctx->target_sample_rate = 48000;
  av_channel_layout_default(&ctx->target_ch_layout, 2); // Force standard Stereo (L/R)
  ctx->target_sample_fmt = AV_SAMPLE_FMT_FLT;           // Force 32-bit float format

  // Allocate and configure the SwrContext using the modern channel layout API.
  // This calculates transition coefficients between the source and target formats.
  ret = swr_alloc_set_opts2(
      &ctx->swr_ctx,
      &ctx->target_ch_layout,          // Output channel layout
      ctx->target_sample_fmt,          // Output sample format (Float32)
      ctx->target_sample_rate,         // Output sample rate (48000 Hz)
      &ctx->audio_dec_ctx->ch_layout,  // Input channel layout (from source codec)
      ctx->audio_dec_ctx->sample_fmt,  // Input sample format (from source codec)
      ctx->audio_dec_ctx->sample_rate, // Input sample rate (from source codec)
      0, NULL);                        // No extra log offset parameters

  // Ensure allocation succeeded before proceeding
  if (ret < 0 || !ctx->swr_ctx)
  {
    return (ret < 0) ? ret : AVERROR(ENOMEM);
  }

  // Initialize the resampler context with the configured parameters
  ret = swr_init(ctx->swr_ctx);
  if (ret < 0)
  {
    swr_free(&ctx->swr_ctx);
    return ret;
  }

  return 0;
}

/**
 * Opens a media file, reads its metadata, and initializes the decoders
 * for both the primary video and audio streams.
 *
 * This function manages the safe, initial step-by-step pipeline discovery:
 *   1. Opens the media file container and parses headers.
 *   2. Extracts packet-level stream descriptors (resolution, codecs, sample rates).
 *   3. Locates the best video stream and opens its corresponding hardware-agnostic decoder.
 *   4. Locates the best audio stream, opens its decoder, and initializes the resampler.
 *
 * If any middle step fails, a unified "fail" label acts as an emergency sweep,
 * freeing partially allocated memory blocks to prevent structural leaks.
 *
 * @param ctx          Pointer to the uninitialized DemuxDecContext structure.
 * @param input_path   System file path to the source video (e.g., MKV, MP4).
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int open_input_and_decoders(DemuxDecContext *ctx, const char *input_path)
{
  int ret;
  ctx->fmt_ctx = NULL;
  ctx->video_stream_idx = -1;
  ctx->audio_stream_idx = -1;
  ctx->video_dec_ctx = NULL;
  ctx->audio_dec_ctx = NULL;
  ctx->swr_ctx = NULL;

  // 1. Open the media file container and extract initial stream parameters
  ret = avformat_open_input(&ctx->fmt_ctx, input_path, NULL, NULL);
  if (ret < 0)
    return ret;

  // 2. Query the stream contents of the container to discover streams
  ret = avformat_find_stream_info(ctx->fmt_ctx, NULL);
  if (ret < 0)
    goto fail;

  // 3. Find and configure the best Video Stream in the container
  const AVCodec *video_codec = NULL;
  ret = av_find_best_stream(ctx->fmt_ctx, AVMEDIA_TYPE_VIDEO, -1, -1, &video_codec, 0);
  if (ret >= 0)
  {
    ctx->video_stream_idx = ret;

    // Allocate raw codec context block
    ctx->video_dec_ctx = avcodec_alloc_context3(video_codec);
    if (!ctx->video_dec_ctx)
    {
      ret = AVERROR(ENOMEM);
      goto fail;
    }

    // Copy stream configurations (width, height, profiles) to the decoder context
    ret = avcodec_parameters_to_context(ctx->video_dec_ctx, ctx->fmt_ctx->streams[ctx->video_stream_idx]->codecpar);
    if (ret < 0)
      goto fail;

    // Initialize and open the decoder thread
    ret = avcodec_open2(ctx->video_dec_ctx, video_codec, NULL);
    if (ret < 0)
      goto fail;
  }

  // 4. Find and configure the best Audio Stream in the container
  const AVCodec *audio_codec = NULL;
  ret = av_find_best_stream(ctx->fmt_ctx, AVMEDIA_TYPE_AUDIO, -1, -1, &audio_codec, 0);
  if (ret >= 0)
  {
    ctx->audio_stream_idx = ret;

    // Allocate raw audio codec context block
    ctx->audio_dec_ctx = avcodec_alloc_context3(audio_codec);
    if (!ctx->audio_dec_ctx)
    {
      ret = AVERROR(ENOMEM);
      goto fail;
    }

    // Copy stream configurations (sample rate, bit-rate, channel layout) to the decoder context
    ret = avcodec_parameters_to_context(ctx->audio_dec_ctx, ctx->fmt_ctx->streams[ctx->audio_stream_idx]->codecpar);
    if (ret < 0)
      goto fail;

    // Initialize and open the audio decoder
    ret = avcodec_open2(ctx->audio_dec_ctx, audio_codec, NULL);
    if (ret < 0)
      goto fail;

    // Initialize swresample to normalize audio for miniaudio
    ret = init_audio_resampler(ctx);
    if (ret < 0)
      goto fail;
  }

  return 0;

fail:
  // Rollback phase: cleanly close allocations in reverse order of initialization
  if (ctx->video_dec_ctx)
    avcodec_free_context(&ctx->video_dec_ctx);
  if (ctx->audio_dec_ctx)
    avcodec_free_context(&ctx->audio_dec_ctx);
  if (ctx->fmt_ctx)
    avformat_close_input(&ctx->fmt_ctx);
  return ret;
}

/**
 * Safely releases, closes, and tears down all resources managed inside
 * the DemuxDecContext, preventing memory leaks between presentation runs.
 *
 * Deallocation operates in strict alignment with ownership rules:
 *   1. Destroys the software resampler context.
 *   2. Deallocates and closes the video and audio decoders.
 *   3. Closes the container format context and releases file descriptors.
 *   4. Frees dynamically allocated channel layout structures.
 *
 * @param ctx   Pointer to the active DemuxDecContext struct to clean up.
 */
void free_demux_dec_context(DemuxDecContext *ctx)
{
  if (!ctx)
    return;

  // Free the resampler context
  if (ctx->swr_ctx)
    swr_free(&ctx->swr_ctx);

  // Free the video decoder resources
  if (ctx->video_dec_ctx)
    avcodec_free_context(&ctx->video_dec_ctx);

  // Free the audio decoder resources
  if (ctx->audio_dec_ctx)
    avcodec_free_context(&ctx->audio_dec_ctx);

  // Close format input and set context back to NULL
  if (ctx->fmt_ctx)
    avformat_close_input(&ctx->fmt_ctx);

  // Uninitialize the custom target channel layout to prevent leaking layout maps
  av_channel_layout_uninit(&ctx->target_ch_layout);
}

/**
 * Custom I/O write callback for the AVIOContext.
 *
 * This function is triggered by the FFmpeg muxer whenever a chunk or fragment
 * of the fragmented MP4 (fMP4) stream is finalized in memory. It immediately
 * passes the pointer and size of the generated binary buffer back to the Go
 * runtime using the registered Go callback function and integer user token.
 *
 * @param opaque    A pointer to the user-defined TranscodeContext struct.
 * @param buf       The raw binary buffer containing fMP4 data.
 * @param buf_size  The size of the buffer in bytes.
 *
 * @return The number of written bytes, representing success or custom error.
 */
static int write_to_memory_cb(void *opaque, const uint8_t *buf, int buf_size)
{
  TranscodeContext *ctx = (TranscodeContext *)opaque;
  if (ctx && ctx->go_callback)
  {
    // Pass the integer token back to Go
    ctx->go_callback((uint8_t *)buf, buf_size, ctx->go_user_token);
  }
  return buf_size;
}

/**
 * Allocates and initializes the output Format Context specifically for
 * fragmented MP4 (fMP4) streaming without using any local filesystem disk I/O.
 *
 * This function handles allocating a custom, dynamic AVIOContext containing
 * a 4KB write-buffer. All data generated by the multiplexing phase is redirected
 * through our 'write_to_memory_cb' directly to Go.
 *
 * @param out_fmt_ctx  Pointer to the uninitialized AVFormatContext pointer.
 * @param tx_ctx       Pointer to the Go callback routing context structure.
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int init_fmp4_muxer(AVFormatContext **out_fmt_ctx, TranscodeContext *tx_ctx)
{
  int ret;
  size_t avio_buf_size = 4096;
  uint8_t *avio_buf = NULL;
  AVIOContext *avio_ctx = NULL;

  ret = avformat_alloc_output_context2(out_fmt_ctx, NULL, "mp4", NULL);
  if (ret < 0)
  {
    return ret;
  }

  avio_buf = (uint8_t *)av_malloc(avio_buf_size);
  if (!avio_buf)
  {
    avformat_free_context(*out_fmt_ctx);
    *out_fmt_ctx = NULL;
    return AVERROR(ENOMEM);
  }

  avio_ctx = avio_alloc_context(
      avio_buf,
      avio_buf_size,
      1,                  // Flag 1 sets the IO context to Write-Only mode
      tx_ctx,             // Passed into callbacks as 'opaque' parameter
      NULL,               // Read callback is unneeded for our live stream output
      write_to_memory_cb, // Primary write interceptor callback
      NULL                // Seek callback is omitted since we can't seek live TCP streams
  );

  if (!avio_ctx)
  {
    av_free(avio_buf);
    avformat_free_context(*out_fmt_ctx);
    *out_fmt_ctx = NULL;
    return AVERROR(ENOMEM);
  }

  (*out_fmt_ctx)->pb = avio_ctx;
  return 0;
}

/**
 * Formats and writes the initial fMP4 container headers to the memory context.
 *
 * This function injects the specific metadata options (`movflags`) required by
 * browser Media Source Extensions (MSE) to begin playback instantly.
 *
 * Options utilized:
 * - 'empty_moov': Writes a clean, frame-index-free structural header immediately.
 * - 'default_base_moof': Resolves frame offsets relative to fragment start points.
 * - 'frag_keyframe': Flushes a play-ready segment on every video keyframe.
 * - 'omit_tfhd_offset': Streamlines file metadata sizing for browser parsing.
 *
 * @param out_fmt_ctx  The output context allocated via init_fmp4_muxer.
 *
 * @return 0 on success, or a negative FFmpeg error code on failure.
 */
int write_fmp4_header(AVFormatContext *out_fmt_ctx)
{
  int ret;
  AVDictionary *opts = NULL;

  ret = av_dict_set(&opts, "movflags", "empty_moov+default_base_moof+frag_keyframe+omit_tfhd_offset", 0);
  if (ret < 0)
  {
    return ret;
  }

  ret = avformat_write_header(out_fmt_ctx, &opts);
  av_dict_free(&opts);
  return ret;
}

/**
 * Safely releases and tears down all allocations associated with the memory-based
 * fMP4 multiplexing context, completely eliminating memory leaks.
 *
 * It extracts the dynamic buffer inside the AVIOContext and frees it in the correct
 * chronological order to prevent dangling pointer faults.
 *
 * @param out_fmt_ctx  The output context to be deallocated.
 */
void free_fmp4_muxer(AVFormatContext *out_fmt_ctx)
{
  if (!out_fmt_ctx)
  {
    return;
  }

  if (out_fmt_ctx->pb)
  {
    // Free the internal dynamic 4KB buffer inside the AVIO structure
    av_freep(&out_fmt_ctx->pb->buffer);
    // Free the custom IO context structure
    avio_context_free(&out_fmt_ctx->pb);
  }

  avformat_free_context(out_fmt_ctx);
}

/**
 * Miniaudio internal playback callback with dynamic A/V drift correction.
 *
 * This callback serves as the high-priority hardware interface, executing
 * asynchronously to stream audio data from the lock-free ring buffer to the
 * sound card.
 *
 * Logic flow:
 * 1. Monitors the 'target_delay_ms' against 'current_delay_samples' to detect
 *    drift introduced by the network/rendering pipeline.
 * 2. Dynamically adjusts the reading rate (speeding up or slowing down)
 *    using sub-millisecond micro-adjustments (max 1.5%) to maintain sync.
 * 3. Applies linear volume ramps during padding insertion to eliminate
 *    audible clicking/popping artifacts during sync corrections.
 * 4. Fallback: Automatically writes silence in the event of ring-buffer
 *    underruns to prevent hardware noise.
 *
 * @param pDevice           Pointer to the active miniaudio device instance.
 * @param pOutput           Target output hardware buffer to fill with PCM frames.
 * @param pInput            Input capture buffer (NULL for our playback-only configuration).
 * @param frameCount        Number of PCM audio frames requested by the sound card.
 */
static void audio_device_callback(ma_device *pDevice, void *pOutput, const void *pInput, ma_uint32 frameCount)
{
  AudioPlaybackContext *play_ctx = (AudioPlaybackContext *)pDevice->pUserData;
  if (!play_ctx || !play_ctx->is_active)
  {
    return;
  }

  int bytes_per_frame = ma_get_bytes_per_frame(ma_format_f32, play_ctx->channels);

  // Read the volatile target offset atomically using compiler builtins
  int target_ms = __atomic_load_n(&play_ctx->target_delay_ms, __ATOMIC_ACQUIRE);
  int target_frames = (target_ms * play_ctx->sample_rate) / 1000;
  int current_balance = __atomic_load_n(&play_ctx->current_delay_samples, __ATOMIC_ACQUIRE);

  ma_uint32 frames_to_read = frameCount;
  int adjustment = 0; // Negative = skip samples (speed up); Positive = insert padding (slow down)

  // Calculate latency gap and determine direction
  if (current_balance < target_frames)
  {
    // We need to slow down to increase latency. Inject up to 1.5% of buffer size as padding
    adjustment = (target_frames - current_balance);
    ma_uint32 max_adjust = frameCount * 0.015;
    if (adjustment > max_adjust)
      adjustment = max_adjust;

    frames_to_read = frameCount - adjustment;
  }
  else if (current_balance > target_frames)
  {
    // We are lagging; we need to speed up. Skip up to 1.5% of buffer size
    adjustment = (current_balance - target_frames);
    ma_uint32 max_adjust = frameCount * 0.015;
    if (adjustment > max_adjust)
      adjustment = max_adjust;

    frames_to_read = frameCount + adjustment;
  }

  ma_uint32 actual_read = frames_to_read;
  void *pReadBuffer;

  // Retrieve requested frames from the thread-safe circular ring buffer
  ma_result result = ma_pcm_rb_acquire_read(&play_ctx->ring_buffer, &actual_read, &pReadBuffer);
  if (result == MA_SUCCESS && actual_read > 0)
  {

    if (frames_to_read < frameCount)
    {
      // SLOW DOWN PATH: Fill the hardware buffer first, then pad the remaining space with silence
      memcpy(pOutput, pReadBuffer, actual_read * bytes_per_frame);

      // Generate a subtle linear ramp-down on the boundary to prevent sudden clicks
      float *out_float = (float *)pOutput;
      int fade_frames = actual_read < 32 ? actual_read : 32;
      for (int i = 0; i < fade_frames; i++)
      {
        float volume = 1.0f - ((float)i / fade_frames);
        for (int c = 0; c < play_ctx->channels; c++)
        {
          out_float[(actual_read - fade_frames + i) * play_ctx->channels + c] *= volume;
        }
      }

      // Zero out (silence) the adjustment padding region
      char *padding_start = (char *)pOutput + (actual_read * bytes_per_frame);
      memset(padding_start, 0, (frameCount - actual_read) * bytes_per_frame);

      // Adjust local delay cursor tracking forward
      __atomic_fetch_add(&play_ctx->current_delay_samples, (frameCount - actual_read), __ATOMIC_RELEASE);
    }
    else if (frames_to_read > frameCount)
    {
      // SPEED UP PATH: We read MORE frames than we write to the hardware device, effectively skipping
      // We copy only the standard frameCount block to output, discarding the extra resampled frames
      memcpy(pOutput, pReadBuffer, frameCount * bytes_per_frame);

      // Adjust local delay cursor tracking backward
      __atomic_fetch_sub(&play_ctx->current_delay_samples, (actual_read - frameCount), __ATOMIC_RELEASE);
    }
    else
    {
      // NORMAL PATH: Perfect synchronization, execute standard copy
      memcpy(pOutput, pReadBuffer, actual_read * bytes_per_frame);
    }

    ma_pcm_rb_commit_read(&play_ctx->ring_buffer, actual_read);
  }
  else
  {
    // Fallback: If ring-buffer is completely starved, immediately write silence
    memset(pOutput, 0, frameCount * bytes_per_frame);
  }
}

/**
 * Initializes the lock-free circular ring-buffer and boots up the miniaudio playback engine.
 *
 * Operating-system-specific hardware routes are selected by translating the backend `device_id` string
 * parameter into a direct physical device reference before starting the background audio thread.
 *
 * @param play_ctx     Pointer to the AudioPlaybackContext instance to manage.
 * @param sample_rate  Audio sampling rate (e.g., 48000 Hz).
 * @param channels     Number of outputs (Stereo = 2 channels).
 * @param device_id    Target hardware device ID string (NULL defaults to OS system default output).
 *
 * @return 0 on success, or a negative integer on allocation or hardware initialization failures.
 */
int init_audio_playback(AudioPlaybackContext *play_ctx, int sample_rate, int channels, const char *device_id)
{
  ma_result result;

  play_ctx->sample_rate = sample_rate;
  play_ctx->channels = channels;
  play_ctx->is_active = 0;

  // 1. Initialize the thread-safe PCM ring buffer.
  // We size the buffer to hold 1.5 seconds of audio frames to absorb pipeline jitter comfortably.
  ma_uint32 buffer_size_frames = sample_rate * 1.5;
  result = ma_pcm_rb_init(ma_format_f32, channels, buffer_size_frames, NULL, NULL, &play_ctx->ring_buffer);
  if (result != MA_SUCCESS)
  {
    return -1;
  }

  // 2. Setup the low-level device configuration
  ma_device_config config = ma_device_config_init(ma_device_type_playback);
  config.playback.format = ma_format_f32;
  config.playback.channels = channels;
  config.sampleRate = sample_rate;
  config.dataCallback = audio_device_callback;
  config.pUserData = play_ctx;

  // To prevent popping, ensure miniaudio uses high-performance hardware buffers
  config.periodSizeInFrames = 480; // ~10ms at 48kHz is standard for stable low-latency routing

  // Parse the device identifier string if specified, otherwise fall back to system default (NULL)
  if (device_id != NULL && strlen(device_id) > 0)
  {
    // On systems utilizing standard character ids, translate or pass direct mapping safely
    // For now, config.playback.pDeviceID supports passing structural addresses
    // Note: The conversion of string -> ma_device_id structure is resolved on the Go layer before calling.
    config.playback.pDeviceID = (ma_device_id *)device_id;
  }
  else
  {
    config.playback.pDeviceID = NULL;
  }

  // 3. Initialize the hardware context link
  result = ma_device_init(NULL, &config, &play_ctx->device);
  if (result != MA_SUCCESS)
  {
    ma_pcm_rb_uninit(&play_ctx->ring_buffer);
    return -2;
  }

  // 4. Start playback thread
  result = ma_device_start(&play_ctx->device);
  if (result != MA_SUCCESS)
  {
    ma_device_uninit(&play_ctx->device);
    ma_pcm_rb_uninit(&play_ctx->ring_buffer);
    return -3;
  }

  play_ctx->is_active = 1;
  return 0;
}

/**
 * Pushes raw, uncompressed PCM floating-point data into the lock-free circular buffer.
 *
 * Called inside the core decoding loop whenever a decoded and resampled audio chunk is finalized.
 *
 * @param play_ctx     Pointer to the active AudioPlaybackContext.
 * @param pcm_data     The resampled input float array.
 * @param frame_count  Number of multi-channel frames contained within the chunk.
 *
 * @return 0 on success, or a negative value if writing to the circular buffer is blocked or overflows.
 */
int write_pcm_to_ring_buffer(AudioPlaybackContext *play_ctx, const float *pcm_data, int frame_count)
{
  if (!play_ctx || !play_ctx->is_active)
  {
    return -1;
  }

  ma_uint32 frames_to_write = frame_count;
  void *pWriteBuffer;

  // Safely acquire writing sector in the circular map
  ma_result result = ma_pcm_rb_acquire_write(&play_ctx->ring_buffer, &frames_to_write, &pWriteBuffer);
  if (result == MA_SUCCESS && frames_to_write > 0)
  {
    int bytes_per_frame = ma_get_bytes_per_frame(ma_format_f32, play_ctx->channels);

    // Copy processed frames into acquired memory
    memcpy(pWriteBuffer, pcm_data, frames_to_write * bytes_per_frame);

    // Finalize transaction to notify the playback reader
    ma_pcm_rb_commit_write(&play_ctx->ring_buffer, frames_to_write);
    return 0;
  }

  return -2; // Buffer overflow/write failed
}

/**
 * Halts the miniaudio hardware playback engine and safely tears down allocated circular buffers.
 *
 * Safe to invoke repeatedly; guarantees complete deallocation of thread structures.
 *
 * @param play_ctx  Pointer to the AudioPlaybackContext to tear down.
 */
void stop_audio_playback(AudioPlaybackContext *play_ctx)
{
  if (!play_ctx)
  {
    return;
  }

  play_ctx->is_active = 0;

  // Uninitialize device - stops background thread natively
  ma_device_uninit(&play_ctx->device);

  // Deallocate local circular structures
  ma_pcm_rb_uninit(&play_ctx->ring_buffer);
}

/**
 * Thread-safely sets the target playback delay offset in milliseconds.
 *
 * This function is called directly from the Go runtime when processing
 * frame latency adjustments received from the webview.
 *
 * @param play_ctx  Pointer to the active AudioPlaybackContext.
 * @param delay_ms  Target delay in milliseconds.
 */
void set_audio_delay_offset(AudioPlaybackContext *play_ctx, int delay_ms)
{
  if (play_ctx)
  {
    __atomic_store_n(&play_ctx->target_delay_ms, delay_ms, __ATOMIC_RELEASE);
  }
}

/**
 * Runs a simulated transcoding loop for testing purposes.
 *
 * This function reads packets linearly from the demuxer context.
 *   - Video packets are written directly into the custom memory-based fMP4 muxer.
 *   - Audio packets are sent to the audio decoder, resampled to Float32 48kHz Stereo,
 *     and instantly committed to the thread-safe miniaudio ring-buffer.
 *
 * To ensure safe execution, the function initializes a temporary muxing pipeline,
 * performs memory allocations, runs the loop for a safe duration (150 video frames),
 * and executes a perfect cleanup of all local buffers upon completion.
 *
 * @param dec_ctx      Pointer to the active and opened DemuxDecContext.
 * @param play_ctx     Pointer to the running AudioPlaybackContext.
 * @param go_token     Integer token wrapping the Go-level channel to route bytes.
 *
 * @return 0 on success, or a negative integer error code on mapping failure.
 */
int run_test_mux_and_play(DemuxDecContext *dec_ctx, AudioPlaybackContext *play_ctx, uintptr_t go_token)
{
  int ret;
  TranscodeContext tx_ctx;
  AVFormatContext *out_fmt_ctx = NULL;
  AVPacket *pkt = NULL;
  AVFrame *frame = NULL;
  float *resample_buf = NULL;
  int frame_count = 0;

  // Set up the Go callback wrapper context using the integer token
  tx_ctx.go_user_token = go_token;
  tx_ctx.go_callback = goTestWriteCallback;

  // Initialize in-memory custom fMP4 muxer
  ret = init_fmp4_muxer(&out_fmt_ctx, &tx_ctx);
  if (ret < 0)
  {
    return ret;
  }

  // ADD THE VIDEO STREAM TO THE OUTPUT MUXER
  if (dec_ctx->video_stream_idx >= 0)
  {
    AVStream *in_stream = dec_ctx->fmt_ctx->streams[dec_ctx->video_stream_idx];
    AVStream *out_stream = avformat_new_stream(out_fmt_ctx, NULL);
    if (!out_stream)
    {
      free_fmp4_muxer(out_fmt_ctx);
      return AVERROR(ENOMEM);
    }

    // Copy the exact codec parameters (H.264/H.265, resolution, etc.) to the new stream
    ret = avcodec_parameters_copy(out_stream->codecpar, in_stream->codecpar);
    if (ret < 0)
    {
      free_fmp4_muxer(out_fmt_ctx);
      return ret;
    }
    out_stream->codecpar->codec_tag = 0; // Clear the codec tag so the MP4 muxer assigns a compliant one
  }

  // Write initial fMP4 segments to spark the browser initialization sequence
  ret = write_fmp4_header(out_fmt_ctx);
  if (ret < 0)
  {
    free_fmp4_muxer(out_fmt_ctx);
    return ret;
  }

  // Allocate frame structures for dynamic decoding operations
  pkt = av_packet_alloc();
  frame = av_frame_alloc();
  resample_buf = (float *)malloc(48000 * 2 * sizeof(float)); // Up to 1-second dynamic buffer block
  if (!pkt || !frame || !resample_buf)
  {
    ret = AVERROR(ENOMEM);
    goto cleanup;
  }

  // Main extraction loop
  while (frame_count < 150)
  {
    ret = av_read_frame(dec_ctx->fmt_ctx, pkt);
    if (ret < 0)
    {
      break; // Stream read finished natively
    }

    if (pkt->stream_index == dec_ctx->video_stream_idx)
    {
      // RESCALE TIMESTAMPS AND MAP STREAM INDEX
      AVStream *in_stream = dec_ctx->fmt_ctx->streams[dec_ctx->video_stream_idx];
      AVStream *out_stream = out_fmt_ctx->streams[0]; // We only mapped 1 stream (video)

      // Rescale presentation/decompression timestamps to the new fMP4 time base
      av_packet_rescale_ts(pkt, in_stream->time_base, out_stream->time_base);

      // Assign the packet to the 0th index (our single output video stream)
      pkt->stream_index = 0;

      // Write frame to fMP4 output context. This fires write_to_memory_cb internally
      av_interleaved_write_frame(out_fmt_ctx, pkt);
      frame_count++;
    }
    else if (pkt->stream_index == dec_ctx->audio_stream_idx)
    {
      // Send raw packet to our audio decoder thread
      ret = avcodec_send_packet(dec_ctx->audio_dec_ctx, pkt);
      if (ret >= 0)
      {
        while (avcodec_receive_frame(dec_ctx->audio_dec_ctx, frame) >= 0)
        {
          // Convert raw source format into native Float32 Stereo 48kHz
          int out_samples = swr_convert(
              dec_ctx->swr_ctx,
              (uint8_t **)&resample_buf,
              48000,
              (const uint8_t **)frame->data,
              frame->nb_samples);

          if (out_samples > 0)
          {
            // Push samples directly into the lock-free circular audio system
            write_pcm_to_ring_buffer(play_ctx, resample_buf, out_samples);
          }
        }
      }
    }
    av_packet_unref(pkt);
  }

  // Force flush the muxer to finalize any pending fragments in the queue
  av_write_trailer(out_fmt_ctx);

cleanup:
  // Safely deallocate all temporary testing allocations
  if (resample_buf)
  {
    free(resample_buf);
  }
  if (frame)
  {
    av_frame_free(&frame);
  }
  if (pkt)
  {
    av_packet_free(&pkt);
  }

  // Finalize stream and write trailers
  if (out_fmt_ctx)
  {
    free_fmp4_muxer(out_fmt_ctx);
  }
  return ret;
}

int get_miniaudio_devices(NativeAudioDevice *devices, int max_devices)
{
  ma_context context;
  if (ma_context_init(NULL, 0, NULL, &context) != MA_SUCCESS)
  {
    return -1;
  }

  ma_device_info *pPlaybackDeviceInfos;
  ma_uint32 playbackDeviceCount;
  if (ma_context_get_devices(&context, &pPlaybackDeviceInfos, &playbackDeviceCount, NULL, NULL) != MA_SUCCESS)
  {
    ma_context_uninit(&context);
    return -2;
  }

  int count = 0;
  for (ma_uint32 i = 0; i < playbackDeviceCount && count < max_devices; i++)
  {
    // Build a unique tracking string from miniaudio raw bytes
    snprintf(devices[count].id, sizeof(devices[count].id), "%u_%u",
             pPlaybackDeviceInfos[i].id.instance.u, i);

    strncpy(devices[count].name, pPlaybackDeviceInfos[i].name, sizeof(devices[count].name) - 1);
    devices[count].is_default = pPlaybackDeviceInfos[i].isDefault;
    count++;
  }

  ma_context_uninit(&context);
  return count;
}