// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlRequest_Action int32

const (
	ControlRequest_PLAY  ControlRequest_Action = 0
	ControlRequest_PAUSE ControlRequest_Action = 1
	ControlRequest_SEEK  ControlRequest_Action = 2
	ControlRequest_STOP  ControlRequest_Action = 3
)

// Enum value maps for ControlRequest_Action.
var (
	ControlRequest_Action_name = map[int32]string{
		0: "PLAY",
		1: "PAUSE",
		2: "SEEK",
		3: "STOP",
	}
	ControlRequest_Action_value = map[string]int32{
		"PLAY":  0,
		"PAUSE": 1,
		"SEEK":  2,
		"STOP":  3,
	}
)

func (x ControlRequest_Action) Enum() *ControlRequest_Action {
	p := new(ControlRequest_Action)
	*p = x
	return p
}

func (x ControlRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stream_proto_enumTypes[0].Descriptor()
}

func (ControlRequest_Action) Type() protoreflect.EnumType {
	return &file_proto_stream_proto_enumTypes[0]
}

func (x ControlRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlRequest_Action.Descriptor instead.
func (ControlRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{6, 0}
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // "preview" or projector screen ID string
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	AudioDeviceId string                 `protobuf:"bytes,3,opt,name=audio_device_id,json=audioDeviceId,proto3" json:"audio_device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *StreamRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *StreamRequest) GetAudioDeviceId() string {
	if x != nil {
		return x.AudioDeviceId
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fmp4Chunk     []byte                 `protobuf:"bytes,1,opt,name=fmp4_chunk,json=fmp4Chunk,proto3" json:"fmp4_chunk,omitempty"` // Raw binary fMP4 segment data
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_proto_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetFmp4Chunk() []byte {
	if x != nil {
		return x.Fmp4Chunk
	}
	return nil
}

type StreamControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControlRequest) Reset() {
	*x = StreamControlRequest{}
	mi := &file_proto_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControlRequest) ProtoMessage() {}

func (x *StreamControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControlRequest.ProtoReflect.Descriptor instead.
func (*StreamControlRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamControlRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type StreamControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControlResponse) Reset() {
	*x = StreamControlResponse{}
	mi := &file_proto_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControlResponse) ProtoMessage() {}

func (x *StreamControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControlResponse.ProtoReflect.Descriptor instead.
func (*StreamControlResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{3}
}

func (x *StreamControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LatencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyRequest) Reset() {
	*x = LatencyRequest{}
	mi := &file_proto_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyRequest) ProtoMessage() {}

func (x *LatencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyRequest.ProtoReflect.Descriptor instead.
func (*LatencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{4}
}

func (x *LatencyRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *LatencyRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type LatencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyResponse) Reset() {
	*x = LatencyResponse{}
	mi := &file_proto_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyResponse) ProtoMessage() {}

func (x *LatencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyResponse.ProtoReflect.Descriptor instead.
func (*LatencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{5}
}

func (x *LatencyResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Action        ControlRequest_Action  `protobuf:"varint,2,opt,name=action,proto3,enum=ffmpeg.ControlRequest_Action" json:"action,omitempty"`
	SeekSeconds   int32                  `protobuf:"varint,3,opt,name=seek_seconds,json=seekSeconds,proto3" json:"seek_seconds,omitempty"` // Only used if action == SEEK
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_proto_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{6}
}

func (x *ControlRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ControlRequest) GetAction() ControlRequest_Action {
	if x != nil {
		return x.Action
	}
	return ControlRequest_PLAY
}

func (x *ControlRequest) GetSeekSeconds() int32 {
	if x != nil {
		return x.SeekSeconds
	}
	return 0
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_proto_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_stream_proto protoreflect.FileDescriptor

const file_proto_stream_proto_rawDesc = "" +
	"\n" +
	"\x12proto/stream.proto\x12\x06ffmpeg\"q\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12&\n" +
	"\x0faudio_device_id\x18\x03 \x01(\tR\raudioDeviceId\"/\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"fmp4_chunk\x18\x01 \x01(\fR\tfmp4Chunk\"3\n" +
	"\x14StreamControlRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"K\n" +
	"\x15StreamControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x0eLatencyRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"-\n" +
	"\x0fLatencyResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xba\x01\n" +
	"\x0eControlRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x125\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1d.ffmpeg.ControlRequest.ActionR\x06action\x12!\n" +
	"\fseek_seconds\x18\x03 \x01(\x05R\vseekSeconds\"1\n" +
	"\x06Action\x12\b\n" +
	"\x04PLAY\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\b\n" +
	"\x04SEEK\x10\x02\x12\b\n" +
	"\x04STOP\x10\x03\"E\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\x9e\x02\n" +
	"\rFFmpegService\x12>\n" +
	"\vStartStream\x12\x15.ffmpeg.StreamRequest\x1a\x16.ffmpeg.StreamResponse0\x01\x12I\n" +
	"\n" +
	"StopStream\x12\x1c.ffmpeg.StreamControlRequest\x1a\x1d.ffmpeg.StreamControlResponse\x12@\n" +
	"\rAdjustLatency\x12\x16.ffmpeg.LatencyRequest\x1a\x17.ffmpeg.LatencyResponse\x12@\n" +
	"\rControlStream\x12\x16.ffmpeg.ControlRequest\x1a\x17.ffmpeg.ControlResponseB(Z&github.com/gotedo/ffmpeg-sidecar/protob\x06proto3"

var (
	file_proto_stream_proto_rawDescOnce sync.Once
	file_proto_stream_proto_rawDescData []byte
)

func file_proto_stream_proto_rawDescGZIP() []byte {
	file_proto_stream_proto_rawDescOnce.Do(func() {
		file_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)))
	})
	return file_proto_stream_proto_rawDescData
}

var file_proto_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_stream_proto_goTypes = []any{
	(ControlRequest_Action)(0),    // 0: ffmpeg.ControlRequest.Action
	(*StreamRequest)(nil),         // 1: ffmpeg.StreamRequest
	(*StreamResponse)(nil),        // 2: ffmpeg.StreamResponse
	(*StreamControlRequest)(nil),  // 3: ffmpeg.StreamControlRequest
	(*StreamControlResponse)(nil), // 4: ffmpeg.StreamControlResponse
	(*LatencyRequest)(nil),        // 5: ffmpeg.LatencyRequest
	(*LatencyResponse)(nil),       // 6: ffmpeg.LatencyResponse
	(*ControlRequest)(nil),        // 7: ffmpeg.ControlRequest
	(*ControlResponse)(nil),       // 8: ffmpeg.ControlResponse
}
var file_proto_stream_proto_depIdxs = []int32{
	0, // 0: ffmpeg.ControlRequest.action:type_name -> ffmpeg.ControlRequest.Action
	1, // 1: ffmpeg.FFmpegService.StartStream:input_type -> ffmpeg.StreamRequest
	3, // 2: ffmpeg.FFmpegService.StopStream:input_type -> ffmpeg.StreamControlRequest
	5, // 3: ffmpeg.FFmpegService.AdjustLatency:input_type -> ffmpeg.LatencyRequest
	7, // 4: ffmpeg.FFmpegService.ControlStream:input_type -> ffmpeg.ControlRequest
	2, // 5: ffmpeg.FFmpegService.StartStream:output_type -> ffmpeg.StreamResponse
	4, // 6: ffmpeg.FFmpegService.StopStream:output_type -> ffmpeg.StreamControlResponse
	6, // 7: ffmpeg.FFmpegService.AdjustLatency:output_type -> ffmpeg.LatencyResponse
	8, // 8: ffmpeg.FFmpegService.ControlStream:output_type -> ffmpeg.ControlResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stream_proto_init() }
func file_proto_stream_proto_init() {
	if File_proto_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stream_proto_goTypes,
		DependencyIndexes: file_proto_stream_proto_depIdxs,
		EnumInfos:         file_proto_stream_proto_enumTypes,
		MessageInfos:      file_proto_stream_proto_msgTypes,
	}.Build()
	File_proto_stream_proto = out.File
	file_proto_stream_proto_goTypes = nil
	file_proto_stream_proto_depIdxs = nil
}
