// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: proto/stream.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FFmpegService_StartStream_FullMethodName        = "/ffmpeg.FFmpegService/StartStream"
	FFmpegService_StopStream_FullMethodName         = "/ffmpeg.FFmpegService/StopStream"
	FFmpegService_AdjustLatency_FullMethodName      = "/ffmpeg.FFmpegService/AdjustLatency"
	FFmpegService_ControlStream_FullMethodName      = "/ffmpeg.FFmpegService/ControlStream"
	FFmpegService_GetAudioDevices_FullMethodName    = "/ffmpeg.FFmpegService/GetAudioDevices"
	FFmpegService_GetMediaProperties_FullMethodName = "/ffmpeg.FFmpegService/GetMediaProperties"
	FFmpegService_GetVideoScreenshot_FullMethodName = "/ffmpeg.FFmpegService/GetVideoScreenshot"
)

// FFmpegServiceClient is the client API for FFmpegService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for controlling and consuming FFmpeg media streams
type FFmpegServiceClient interface {
	// StartStream initializes the decoding/muxing pipeline
	StartStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
	// StopStream terminates an active sidecar pipeline
	StopStream(ctx context.Context, in *StreamControlRequest, opts ...grpc.CallOption) (*StreamControlResponse, error)
	// AdjustLatency sends real-time drift correction commands to the sidecar
	AdjustLatency(ctx context.Context, in *LatencyRequest, opts ...grpc.CallOption) (*LatencyResponse, error)
	// Unified control RPC for playback operations
	ControlStream(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error)
	// GetAudioDevices returns available audio devices to the client
	GetAudioDevices(ctx context.Context, in *DevicesRequest, opts ...grpc.CallOption) (*DevicesResponse, error)
	// Probe metadata properties directly via static analysis
	GetMediaProperties(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error)
	// Extract a standalone compressed frame at a specific offset
	GetVideoScreenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
}

type fFmpegServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFFmpegServiceClient(cc grpc.ClientConnInterface) FFmpegServiceClient {
	return &fFmpegServiceClient{cc}
}

func (c *fFmpegServiceClient) StartStream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &FFmpegService_ServiceDesc.Streams[0], FFmpegService_StartStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegService_StartStreamClient = grpc.ServerStreamingClient[StreamResponse]

func (c *fFmpegServiceClient) StopStream(ctx context.Context, in *StreamControlRequest, opts ...grpc.CallOption) (*StreamControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StreamControlResponse)
	err := c.cc.Invoke(ctx, FFmpegService_StopStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegServiceClient) AdjustLatency(ctx context.Context, in *LatencyRequest, opts ...grpc.CallOption) (*LatencyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LatencyResponse)
	err := c.cc.Invoke(ctx, FFmpegService_AdjustLatency_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegServiceClient) ControlStream(ctx context.Context, in *ControlRequest, opts ...grpc.CallOption) (*ControlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ControlResponse)
	err := c.cc.Invoke(ctx, FFmpegService_ControlStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegServiceClient) GetAudioDevices(ctx context.Context, in *DevicesRequest, opts ...grpc.CallOption) (*DevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DevicesResponse)
	err := c.cc.Invoke(ctx, FFmpegService_GetAudioDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegServiceClient) GetMediaProperties(ctx context.Context, in *MetadataRequest, opts ...grpc.CallOption) (*MetadataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MetadataResponse)
	err := c.cc.Invoke(ctx, FFmpegService_GetMediaProperties_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fFmpegServiceClient) GetVideoScreenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotResponse)
	err := c.cc.Invoke(ctx, FFmpegService_GetVideoScreenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FFmpegServiceServer is the server API for FFmpegService service.
// All implementations must embed UnimplementedFFmpegServiceServer
// for forward compatibility.
//
// Service for controlling and consuming FFmpeg media streams
type FFmpegServiceServer interface {
	// StartStream initializes the decoding/muxing pipeline
	StartStream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
	// StopStream terminates an active sidecar pipeline
	StopStream(context.Context, *StreamControlRequest) (*StreamControlResponse, error)
	// AdjustLatency sends real-time drift correction commands to the sidecar
	AdjustLatency(context.Context, *LatencyRequest) (*LatencyResponse, error)
	// Unified control RPC for playback operations
	ControlStream(context.Context, *ControlRequest) (*ControlResponse, error)
	// GetAudioDevices returns available audio devices to the client
	GetAudioDevices(context.Context, *DevicesRequest) (*DevicesResponse, error)
	// Probe metadata properties directly via static analysis
	GetMediaProperties(context.Context, *MetadataRequest) (*MetadataResponse, error)
	// Extract a standalone compressed frame at a specific offset
	GetVideoScreenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	mustEmbedUnimplementedFFmpegServiceServer()
}

// UnimplementedFFmpegServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFFmpegServiceServer struct{}

func (UnimplementedFFmpegServiceServer) StartStream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Error(codes.Unimplemented, "method StartStream not implemented")
}
func (UnimplementedFFmpegServiceServer) StopStream(context.Context, *StreamControlRequest) (*StreamControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopStream not implemented")
}
func (UnimplementedFFmpegServiceServer) AdjustLatency(context.Context, *LatencyRequest) (*LatencyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AdjustLatency not implemented")
}
func (UnimplementedFFmpegServiceServer) ControlStream(context.Context, *ControlRequest) (*ControlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ControlStream not implemented")
}
func (UnimplementedFFmpegServiceServer) GetAudioDevices(context.Context, *DevicesRequest) (*DevicesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAudioDevices not implemented")
}
func (UnimplementedFFmpegServiceServer) GetMediaProperties(context.Context, *MetadataRequest) (*MetadataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMediaProperties not implemented")
}
func (UnimplementedFFmpegServiceServer) GetVideoScreenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetVideoScreenshot not implemented")
}
func (UnimplementedFFmpegServiceServer) mustEmbedUnimplementedFFmpegServiceServer() {}
func (UnimplementedFFmpegServiceServer) testEmbeddedByValue()                       {}

// UnsafeFFmpegServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FFmpegServiceServer will
// result in compilation errors.
type UnsafeFFmpegServiceServer interface {
	mustEmbedUnimplementedFFmpegServiceServer()
}

func RegisterFFmpegServiceServer(s grpc.ServiceRegistrar, srv FFmpegServiceServer) {
	// If the following call panics, it indicates UnimplementedFFmpegServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FFmpegService_ServiceDesc, srv)
}

func _FFmpegService_StartStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FFmpegServiceServer).StartStream(m, &grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type FFmpegService_StartStreamServer = grpc.ServerStreamingServer[StreamResponse]

func _FFmpegService_StopStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StreamControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegServiceServer).StopStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegService_StopStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegServiceServer).StopStream(ctx, req.(*StreamControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegService_AdjustLatency_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LatencyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegServiceServer).AdjustLatency(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegService_AdjustLatency_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegServiceServer).AdjustLatency(ctx, req.(*LatencyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegService_ControlStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ControlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegServiceServer).ControlStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegService_ControlStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegServiceServer).ControlStream(ctx, req.(*ControlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegService_GetAudioDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegServiceServer).GetAudioDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegService_GetAudioDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegServiceServer).GetAudioDevices(ctx, req.(*DevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegService_GetMediaProperties_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MetadataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegServiceServer).GetMediaProperties(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegService_GetMediaProperties_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegServiceServer).GetMediaProperties(ctx, req.(*MetadataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FFmpegService_GetVideoScreenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FFmpegServiceServer).GetVideoScreenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FFmpegService_GetVideoScreenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FFmpegServiceServer).GetVideoScreenshot(ctx, req.(*ScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FFmpegService_ServiceDesc is the grpc.ServiceDesc for FFmpegService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FFmpegService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ffmpeg.FFmpegService",
	HandlerType: (*FFmpegServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StopStream",
			Handler:    _FFmpegService_StopStream_Handler,
		},
		{
			MethodName: "AdjustLatency",
			Handler:    _FFmpegService_AdjustLatency_Handler,
		},
		{
			MethodName: "ControlStream",
			Handler:    _FFmpegService_ControlStream_Handler,
		},
		{
			MethodName: "GetAudioDevices",
			Handler:    _FFmpegService_GetAudioDevices_Handler,
		},
		{
			MethodName: "GetMediaProperties",
			Handler:    _FFmpegService_GetMediaProperties_Handler,
		},
		{
			MethodName: "GetVideoScreenshot",
			Handler:    _FFmpegService_GetVideoScreenshot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StartStream",
			Handler:       _FFmpegService_StartStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/stream.proto",
}
