// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/stream.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlRequest_Action int32

const (
	ControlRequest_PLAY  ControlRequest_Action = 0
	ControlRequest_PAUSE ControlRequest_Action = 1
	ControlRequest_SEEK  ControlRequest_Action = 2
	ControlRequest_STOP  ControlRequest_Action = 3
)

// Enum value maps for ControlRequest_Action.
var (
	ControlRequest_Action_name = map[int32]string{
		0: "PLAY",
		1: "PAUSE",
		2: "SEEK",
		3: "STOP",
	}
	ControlRequest_Action_value = map[string]int32{
		"PLAY":  0,
		"PAUSE": 1,
		"SEEK":  2,
		"STOP":  3,
	}
)

func (x ControlRequest_Action) Enum() *ControlRequest_Action {
	p := new(ControlRequest_Action)
	*p = x
	return p
}

func (x ControlRequest_Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlRequest_Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_stream_proto_enumTypes[0].Descriptor()
}

func (ControlRequest_Action) Type() protoreflect.EnumType {
	return &file_proto_stream_proto_enumTypes[0]
}

func (x ControlRequest_Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlRequest_Action.Descriptor instead.
func (ControlRequest_Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{6, 0}
}

type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"` // "preview" or projector screen ID string
	FilePath      string                 `protobuf:"bytes,2,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	AudioDeviceId string                 `protobuf:"bytes,3,opt,name=audio_device_id,json=audioDeviceId,proto3" json:"audio_device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_proto_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{0}
}

func (x *StreamRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *StreamRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *StreamRequest) GetAudioDeviceId() string {
	if x != nil {
		return x.AudioDeviceId
	}
	return ""
}

type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fmp4Chunk     []byte                 `protobuf:"bytes,1,opt,name=fmp4_chunk,json=fmp4Chunk,proto3" json:"fmp4_chunk,omitempty"` // Raw binary fMP4 segment data
	Pts           float64                `protobuf:"fixed64,2,opt,name=pts,proto3" json:"pts,omitempty"`                            // Current presentation timestamp of the muxed chunk in seconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_proto_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetFmp4Chunk() []byte {
	if x != nil {
		return x.Fmp4Chunk
	}
	return nil
}

func (x *StreamResponse) GetPts() float64 {
	if x != nil {
		return x.Pts
	}
	return 0
}

type StreamControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControlRequest) Reset() {
	*x = StreamControlRequest{}
	mi := &file_proto_stream_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControlRequest) ProtoMessage() {}

func (x *StreamControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControlRequest.ProtoReflect.Descriptor instead.
func (*StreamControlRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{2}
}

func (x *StreamControlRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

type StreamControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamControlResponse) Reset() {
	*x = StreamControlResponse{}
	mi := &file_proto_stream_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamControlResponse) ProtoMessage() {}

func (x *StreamControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamControlResponse.ProtoReflect.Descriptor instead.
func (*StreamControlResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{3}
}

func (x *StreamControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StreamControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type LatencyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	DelayMs       int32                  `protobuf:"varint,2,opt,name=delay_ms,json=delayMs,proto3" json:"delay_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyRequest) Reset() {
	*x = LatencyRequest{}
	mi := &file_proto_stream_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyRequest) ProtoMessage() {}

func (x *LatencyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyRequest.ProtoReflect.Descriptor instead.
func (*LatencyRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{4}
}

func (x *LatencyRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *LatencyRequest) GetDelayMs() int32 {
	if x != nil {
		return x.DelayMs
	}
	return 0
}

type LatencyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatencyResponse) Reset() {
	*x = LatencyResponse{}
	mi := &file_proto_stream_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatencyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatencyResponse) ProtoMessage() {}

func (x *LatencyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatencyResponse.ProtoReflect.Descriptor instead.
func (*LatencyResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{5}
}

func (x *LatencyResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type ControlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetId      string                 `protobuf:"bytes,1,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	Action        ControlRequest_Action  `protobuf:"varint,2,opt,name=action,proto3,enum=ffmpeg.ControlRequest_Action" json:"action,omitempty"`
	SeekSeconds   int32                  `protobuf:"varint,3,opt,name=seek_seconds,json=seekSeconds,proto3" json:"seek_seconds,omitempty"` // Only used if action == SEEK
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlRequest) Reset() {
	*x = ControlRequest{}
	mi := &file_proto_stream_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlRequest) ProtoMessage() {}

func (x *ControlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlRequest.ProtoReflect.Descriptor instead.
func (*ControlRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{6}
}

func (x *ControlRequest) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *ControlRequest) GetAction() ControlRequest_Action {
	if x != nil {
		return x.Action
	}
	return ControlRequest_PLAY
}

func (x *ControlRequest) GetSeekSeconds() int32 {
	if x != nil {
		return x.SeekSeconds
	}
	return 0
}

type ControlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlResponse) Reset() {
	*x = ControlResponse{}
	mi := &file_proto_stream_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlResponse) ProtoMessage() {}

func (x *ControlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlResponse.ProtoReflect.Descriptor instead.
func (*ControlResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{7}
}

func (x *ControlResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ControlResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DevicesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicesRequest) Reset() {
	*x = DevicesRequest{}
	mi := &file_proto_stream_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesRequest) ProtoMessage() {}

func (x *DevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesRequest.ProtoReflect.Descriptor instead.
func (*DevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{8}
}

type AudioDevice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IsDefault     bool                   `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AudioDevice) Reset() {
	*x = AudioDevice{}
	mi := &file_proto_stream_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AudioDevice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AudioDevice) ProtoMessage() {}

func (x *AudioDevice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AudioDevice.ProtoReflect.Descriptor instead.
func (*AudioDevice) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{9}
}

func (x *AudioDevice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AudioDevice) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AudioDevice) GetIsDefault() bool {
	if x != nil {
		return x.IsDefault
	}
	return false
}

type DevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*AudioDevice         `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DevicesResponse) Reset() {
	*x = DevicesResponse{}
	mi := &file_proto_stream_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DevicesResponse) ProtoMessage() {}

func (x *DevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DevicesResponse.ProtoReflect.Descriptor instead.
func (*DevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{10}
}

func (x *DevicesResponse) GetDevices() []*AudioDevice {
	if x != nil {
		return x.Devices
	}
	return nil
}

type MetadataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataRequest) Reset() {
	*x = MetadataRequest{}
	mi := &file_proto_stream_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataRequest) ProtoMessage() {}

func (x *MetadataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataRequest.ProtoReflect.Descriptor instead.
func (*MetadataRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{11}
}

func (x *MetadataRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

type MetadataResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Container Format Information
	FormatName     string `protobuf:"bytes,1,opt,name=format_name,json=formatName,proto3" json:"format_name,omitempty"`               // e.g., "mov,mp4,m4a,3gp,3g2,mj2" or "matroska,webm"
	FormatLongName string `protobuf:"bytes,2,opt,name=format_long_name,json=formatLongName,proto3" json:"format_long_name,omitempty"` // e.g., "QuickTime / MOV"
	DurationMs     int64  `protobuf:"varint,3,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`              // Total duration mapped to milliseconds
	FileSizeBytes  int64  `protobuf:"varint,4,opt,name=file_size_bytes,json=fileSizeBytes,proto3" json:"file_size_bytes,omitempty"`   // Direct file size on disk
	BitRate        int64  `protobuf:"varint,5,opt,name=bit_rate,json=bitRate,proto3" json:"bit_rate,omitempty"`                       // Total stream tracking bitrate (bps)
	// Core Extracted Tag Metadata
	Title        string `protobuf:"bytes,6,opt,name=title,proto3" json:"title,omitempty"`
	Author       string `protobuf:"bytes,7,opt,name=author,proto3" json:"author,omitempty"` // Maps to "artist" / "author"
	Album        string `protobuf:"bytes,8,opt,name=album,proto3" json:"album,omitempty"`
	Track        string `protobuf:"bytes,9,opt,name=track,proto3" json:"track,omitempty"`
	Genre        string `protobuf:"bytes,10,opt,name=genre,proto3" json:"genre,omitempty"`
	CreationTime string `protobuf:"bytes,11,opt,name=creation_time,json=creationTime,proto3" json:"creation_time,omitempty"` // ISO timestamp or raw tag string
	LastModified string `protobuf:"bytes,12,opt,name=last_modified,json=lastModified,proto3" json:"last_modified,omitempty"`
	// Primary Video Stream Parameters
	HasVideo           bool    `protobuf:"varint,13,opt,name=has_video,json=hasVideo,proto3" json:"has_video,omitempty"`
	VideoCodec         string  `protobuf:"bytes,14,opt,name=video_codec,json=videoCodec,proto3" json:"video_codec,omitempty"` // e.g., "h264", "hevc", "vp9"
	VideoCodecLongName string  `protobuf:"bytes,15,opt,name=video_codec_long_name,json=videoCodecLongName,proto3" json:"video_codec_long_name,omitempty"`
	VideoProfile       string  `protobuf:"bytes,16,opt,name=video_profile,json=videoProfile,proto3" json:"video_profile,omitempty"` // e.g., "Main", "High", "Main 10"
	Width              int32   `protobuf:"varint,17,opt,name=width,proto3" json:"width,omitempty"`
	Height             int32   `protobuf:"varint,18,opt,name=height,proto3" json:"height,omitempty"`
	Framerate          float64 `protobuf:"fixed64,19,opt,name=framerate,proto3" json:"framerate,omitempty"`                               // Computed float value (fps)
	AspectRatio        string  `protobuf:"bytes,20,opt,name=aspect_ratio,json=aspectRatio,proto3" json:"aspect_ratio,omitempty"`          // Display Aspect Ratio string (e.g., "16:9")
	PixelFormat        string  `protobuf:"bytes,21,opt,name=pixel_format,json=pixelFormat,proto3" json:"pixel_format,omitempty"`          // e.g., "yuv420p", "yuv420p10le"
	ColorSpace         string  `protobuf:"bytes,22,opt,name=color_space,json=colorSpace,proto3" json:"color_space,omitempty"`             // e.g., "bt709", "bt2020nc"
	ColorTransfer      string  `protobuf:"bytes,23,opt,name=color_transfer,json=colorTransfer,proto3" json:"color_transfer,omitempty"`    // e.g., "arib-std-b67", "smpte2084"
	ColorPrimaries     string  `protobuf:"bytes,24,opt,name=color_primaries,json=colorPrimaries,proto3" json:"color_primaries,omitempty"` // e.g., "bt2020"
	// Primary Audio Stream Parameters
	HasAudio           bool   `protobuf:"varint,25,opt,name=has_audio,json=hasAudio,proto3" json:"has_audio,omitempty"`
	AudioCodec         string `protobuf:"bytes,26,opt,name=audio_codec,json=audioCodec,proto3" json:"audio_codec,omitempty"` // e.g., "aac", "opus", "mp3"
	AudioCodecLongName string `protobuf:"bytes,27,opt,name=audio_codec_long_name,json=audioCodecLongName,proto3" json:"audio_codec_long_name,omitempty"`
	AudioProfile       string `protobuf:"bytes,28,opt,name=audio_profile,json=audioProfile,proto3" json:"audio_profile,omitempty"`     // e.g., "LC", "HE"
	AudioChannels      int32  `protobuf:"varint,29,opt,name=audio_channels,json=audioChannels,proto3" json:"audio_channels,omitempty"` // Total audio channels detected
	SampleRate         int32  `protobuf:"varint,30,opt,name=sample_rate,json=sampleRate,proto3" json:"sample_rate,omitempty"`          // Audio sampling clock rate (Hz, e.g., 48000)
	ChannelLayout      string `protobuf:"bytes,31,opt,name=channel_layout,json=channelLayout,proto3" json:"channel_layout,omitempty"`  // e.g., "stereo", "5.1(side)", "mono"
	AudioBitRate       int64  `protobuf:"varint,32,opt,name=audio_bit_rate,json=audioBitRate,proto3" json:"audio_bit_rate,omitempty"`  // Audio track individual operational bitrate
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *MetadataResponse) Reset() {
	*x = MetadataResponse{}
	mi := &file_proto_stream_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataResponse) ProtoMessage() {}

func (x *MetadataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataResponse.ProtoReflect.Descriptor instead.
func (*MetadataResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{12}
}

func (x *MetadataResponse) GetFormatName() string {
	if x != nil {
		return x.FormatName
	}
	return ""
}

func (x *MetadataResponse) GetFormatLongName() string {
	if x != nil {
		return x.FormatLongName
	}
	return ""
}

func (x *MetadataResponse) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *MetadataResponse) GetFileSizeBytes() int64 {
	if x != nil {
		return x.FileSizeBytes
	}
	return 0
}

func (x *MetadataResponse) GetBitRate() int64 {
	if x != nil {
		return x.BitRate
	}
	return 0
}

func (x *MetadataResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MetadataResponse) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *MetadataResponse) GetAlbum() string {
	if x != nil {
		return x.Album
	}
	return ""
}

func (x *MetadataResponse) GetTrack() string {
	if x != nil {
		return x.Track
	}
	return ""
}

func (x *MetadataResponse) GetGenre() string {
	if x != nil {
		return x.Genre
	}
	return ""
}

func (x *MetadataResponse) GetCreationTime() string {
	if x != nil {
		return x.CreationTime
	}
	return ""
}

func (x *MetadataResponse) GetLastModified() string {
	if x != nil {
		return x.LastModified
	}
	return ""
}

func (x *MetadataResponse) GetHasVideo() bool {
	if x != nil {
		return x.HasVideo
	}
	return false
}

func (x *MetadataResponse) GetVideoCodec() string {
	if x != nil {
		return x.VideoCodec
	}
	return ""
}

func (x *MetadataResponse) GetVideoCodecLongName() string {
	if x != nil {
		return x.VideoCodecLongName
	}
	return ""
}

func (x *MetadataResponse) GetVideoProfile() string {
	if x != nil {
		return x.VideoProfile
	}
	return ""
}

func (x *MetadataResponse) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MetadataResponse) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MetadataResponse) GetFramerate() float64 {
	if x != nil {
		return x.Framerate
	}
	return 0
}

func (x *MetadataResponse) GetAspectRatio() string {
	if x != nil {
		return x.AspectRatio
	}
	return ""
}

func (x *MetadataResponse) GetPixelFormat() string {
	if x != nil {
		return x.PixelFormat
	}
	return ""
}

func (x *MetadataResponse) GetColorSpace() string {
	if x != nil {
		return x.ColorSpace
	}
	return ""
}

func (x *MetadataResponse) GetColorTransfer() string {
	if x != nil {
		return x.ColorTransfer
	}
	return ""
}

func (x *MetadataResponse) GetColorPrimaries() string {
	if x != nil {
		return x.ColorPrimaries
	}
	return ""
}

func (x *MetadataResponse) GetHasAudio() bool {
	if x != nil {
		return x.HasAudio
	}
	return false
}

func (x *MetadataResponse) GetAudioCodec() string {
	if x != nil {
		return x.AudioCodec
	}
	return ""
}

func (x *MetadataResponse) GetAudioCodecLongName() string {
	if x != nil {
		return x.AudioCodecLongName
	}
	return ""
}

func (x *MetadataResponse) GetAudioProfile() string {
	if x != nil {
		return x.AudioProfile
	}
	return ""
}

func (x *MetadataResponse) GetAudioChannels() int32 {
	if x != nil {
		return x.AudioChannels
	}
	return 0
}

func (x *MetadataResponse) GetSampleRate() int32 {
	if x != nil {
		return x.SampleRate
	}
	return 0
}

func (x *MetadataResponse) GetChannelLayout() string {
	if x != nil {
		return x.ChannelLayout
	}
	return ""
}

func (x *MetadataResponse) GetAudioBitRate() int64 {
	if x != nil {
		return x.AudioBitRate
	}
	return 0
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilePath      string                 `protobuf:"bytes,1,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	TimeMs        int64                  `protobuf:"varint,2,opt,name=time_ms,json=timeMs,proto3" json:"time_ms,omitempty"` // Configurable video timeline point in milliseconds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_proto_stream_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{13}
}

func (x *ScreenshotRequest) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *ScreenshotRequest) GetTimeMs() int64 {
	if x != nil {
		return x.TimeMs
	}
	return 0
}

type ScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // Raw compressed image buffer (e.g., JPEG or PNG)
	MimeType      string                 `protobuf:"bytes,2,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`    // "image/jpeg" or "image/png" matching encoder
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_proto_stream_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{14}
}

func (x *ScreenshotResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ScreenshotResponse) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

type ShutdownRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownRequest) Reset() {
	*x = ShutdownRequest{}
	mi := &file_proto_stream_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownRequest) ProtoMessage() {}

func (x *ShutdownRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownRequest.ProtoReflect.Descriptor instead.
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{15}
}

type ShutdownResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShutdownResponse) Reset() {
	*x = ShutdownResponse{}
	mi := &file_proto_stream_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShutdownResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShutdownResponse) ProtoMessage() {}

func (x *ShutdownResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stream_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShutdownResponse.ProtoReflect.Descriptor instead.
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return file_proto_stream_proto_rawDescGZIP(), []int{16}
}

func (x *ShutdownResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

var File_proto_stream_proto protoreflect.FileDescriptor

const file_proto_stream_proto_rawDesc = "" +
	"\n" +
	"\x12proto/stream.proto\x12\x06ffmpeg\"q\n" +
	"\rStreamRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1b\n" +
	"\tfile_path\x18\x02 \x01(\tR\bfilePath\x12&\n" +
	"\x0faudio_device_id\x18\x03 \x01(\tR\raudioDeviceId\"A\n" +
	"\x0eStreamResponse\x12\x1d\n" +
	"\n" +
	"fmp4_chunk\x18\x01 \x01(\fR\tfmp4Chunk\x12\x10\n" +
	"\x03pts\x18\x02 \x01(\x01R\x03pts\"3\n" +
	"\x14StreamControlRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\"K\n" +
	"\x15StreamControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"H\n" +
	"\x0eLatencyRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x19\n" +
	"\bdelay_ms\x18\x02 \x01(\x05R\adelayMs\"-\n" +
	"\x0fLatencyResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"\xba\x01\n" +
	"\x0eControlRequest\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x125\n" +
	"\x06action\x18\x02 \x01(\x0e2\x1d.ffmpeg.ControlRequest.ActionR\x06action\x12!\n" +
	"\fseek_seconds\x18\x03 \x01(\x05R\vseekSeconds\"1\n" +
	"\x06Action\x12\b\n" +
	"\x04PLAY\x10\x00\x12\t\n" +
	"\x05PAUSE\x10\x01\x12\b\n" +
	"\x04SEEK\x10\x02\x12\b\n" +
	"\x04STOP\x10\x03\"E\n" +
	"\x0fControlResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x10\n" +
	"\x0eDevicesRequest\"P\n" +
	"\vAudioDevice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"is_default\x18\x03 \x01(\bR\tisDefault\"@\n" +
	"\x0fDevicesResponse\x12-\n" +
	"\adevices\x18\x01 \x03(\v2\x13.ffmpeg.AudioDeviceR\adevices\".\n" +
	"\x0fMetadataRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\"\xbf\b\n" +
	"\x10MetadataResponse\x12\x1f\n" +
	"\vformat_name\x18\x01 \x01(\tR\n" +
	"formatName\x12(\n" +
	"\x10format_long_name\x18\x02 \x01(\tR\x0eformatLongName\x12\x1f\n" +
	"\vduration_ms\x18\x03 \x01(\x03R\n" +
	"durationMs\x12&\n" +
	"\x0ffile_size_bytes\x18\x04 \x01(\x03R\rfileSizeBytes\x12\x19\n" +
	"\bbit_rate\x18\x05 \x01(\x03R\abitRate\x12\x14\n" +
	"\x05title\x18\x06 \x01(\tR\x05title\x12\x16\n" +
	"\x06author\x18\a \x01(\tR\x06author\x12\x14\n" +
	"\x05album\x18\b \x01(\tR\x05album\x12\x14\n" +
	"\x05track\x18\t \x01(\tR\x05track\x12\x14\n" +
	"\x05genre\x18\n" +
	" \x01(\tR\x05genre\x12#\n" +
	"\rcreation_time\x18\v \x01(\tR\fcreationTime\x12#\n" +
	"\rlast_modified\x18\f \x01(\tR\flastModified\x12\x1b\n" +
	"\thas_video\x18\r \x01(\bR\bhasVideo\x12\x1f\n" +
	"\vvideo_codec\x18\x0e \x01(\tR\n" +
	"videoCodec\x121\n" +
	"\x15video_codec_long_name\x18\x0f \x01(\tR\x12videoCodecLongName\x12#\n" +
	"\rvideo_profile\x18\x10 \x01(\tR\fvideoProfile\x12\x14\n" +
	"\x05width\x18\x11 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x12 \x01(\x05R\x06height\x12\x1c\n" +
	"\tframerate\x18\x13 \x01(\x01R\tframerate\x12!\n" +
	"\faspect_ratio\x18\x14 \x01(\tR\vaspectRatio\x12!\n" +
	"\fpixel_format\x18\x15 \x01(\tR\vpixelFormat\x12\x1f\n" +
	"\vcolor_space\x18\x16 \x01(\tR\n" +
	"colorSpace\x12%\n" +
	"\x0ecolor_transfer\x18\x17 \x01(\tR\rcolorTransfer\x12'\n" +
	"\x0fcolor_primaries\x18\x18 \x01(\tR\x0ecolorPrimaries\x12\x1b\n" +
	"\thas_audio\x18\x19 \x01(\bR\bhasAudio\x12\x1f\n" +
	"\vaudio_codec\x18\x1a \x01(\tR\n" +
	"audioCodec\x121\n" +
	"\x15audio_codec_long_name\x18\x1b \x01(\tR\x12audioCodecLongName\x12#\n" +
	"\raudio_profile\x18\x1c \x01(\tR\faudioProfile\x12%\n" +
	"\x0eaudio_channels\x18\x1d \x01(\x05R\raudioChannels\x12\x1f\n" +
	"\vsample_rate\x18\x1e \x01(\x05R\n" +
	"sampleRate\x12%\n" +
	"\x0echannel_layout\x18\x1f \x01(\tR\rchannelLayout\x12$\n" +
	"\x0eaudio_bit_rate\x18  \x01(\x03R\faudioBitRate\"I\n" +
	"\x11ScreenshotRequest\x12\x1b\n" +
	"\tfile_path\x18\x01 \x01(\tR\bfilePath\x12\x17\n" +
	"\atime_ms\x18\x02 \x01(\x03R\x06timeMs\"P\n" +
	"\x12ScreenshotResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x1b\n" +
	"\tmime_type\x18\x02 \x01(\tR\bmimeType\"\x11\n" +
	"\x0fShutdownRequest\".\n" +
	"\x10ShutdownResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted2\xb7\x04\n" +
	"\rFFmpegService\x12>\n" +
	"\vStartStream\x12\x15.ffmpeg.StreamRequest\x1a\x16.ffmpeg.StreamResponse0\x01\x12I\n" +
	"\n" +
	"StopStream\x12\x1c.ffmpeg.StreamControlRequest\x1a\x1d.ffmpeg.StreamControlResponse\x12@\n" +
	"\rAdjustLatency\x12\x16.ffmpeg.LatencyRequest\x1a\x17.ffmpeg.LatencyResponse\x12@\n" +
	"\rControlStream\x12\x16.ffmpeg.ControlRequest\x1a\x17.ffmpeg.ControlResponse\x12B\n" +
	"\x0fGetAudioDevices\x12\x16.ffmpeg.DevicesRequest\x1a\x17.ffmpeg.DevicesResponse\x12G\n" +
	"\x12GetMediaProperties\x12\x17.ffmpeg.MetadataRequest\x1a\x18.ffmpeg.MetadataResponse\x12K\n" +
	"\x12GetVideoScreenshot\x12\x19.ffmpeg.ScreenshotRequest\x1a\x1a.ffmpeg.ScreenshotResponse\x12=\n" +
	"\bShutdown\x12\x17.ffmpeg.ShutdownRequest\x1a\x18.ffmpeg.ShutdownResponseB7Z5github.com/gotedo/gotedo-impress-ffmpeg-sidecar/protob\x06proto3"

var (
	file_proto_stream_proto_rawDescOnce sync.Once
	file_proto_stream_proto_rawDescData []byte
)

func file_proto_stream_proto_rawDescGZIP() []byte {
	file_proto_stream_proto_rawDescOnce.Do(func() {
		file_proto_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)))
	})
	return file_proto_stream_proto_rawDescData
}

var file_proto_stream_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_proto_stream_proto_goTypes = []any{
	(ControlRequest_Action)(0),    // 0: ffmpeg.ControlRequest.Action
	(*StreamRequest)(nil),         // 1: ffmpeg.StreamRequest
	(*StreamResponse)(nil),        // 2: ffmpeg.StreamResponse
	(*StreamControlRequest)(nil),  // 3: ffmpeg.StreamControlRequest
	(*StreamControlResponse)(nil), // 4: ffmpeg.StreamControlResponse
	(*LatencyRequest)(nil),        // 5: ffmpeg.LatencyRequest
	(*LatencyResponse)(nil),       // 6: ffmpeg.LatencyResponse
	(*ControlRequest)(nil),        // 7: ffmpeg.ControlRequest
	(*ControlResponse)(nil),       // 8: ffmpeg.ControlResponse
	(*DevicesRequest)(nil),        // 9: ffmpeg.DevicesRequest
	(*AudioDevice)(nil),           // 10: ffmpeg.AudioDevice
	(*DevicesResponse)(nil),       // 11: ffmpeg.DevicesResponse
	(*MetadataRequest)(nil),       // 12: ffmpeg.MetadataRequest
	(*MetadataResponse)(nil),      // 13: ffmpeg.MetadataResponse
	(*ScreenshotRequest)(nil),     // 14: ffmpeg.ScreenshotRequest
	(*ScreenshotResponse)(nil),    // 15: ffmpeg.ScreenshotResponse
	(*ShutdownRequest)(nil),       // 16: ffmpeg.ShutdownRequest
	(*ShutdownResponse)(nil),      // 17: ffmpeg.ShutdownResponse
}
var file_proto_stream_proto_depIdxs = []int32{
	0,  // 0: ffmpeg.ControlRequest.action:type_name -> ffmpeg.ControlRequest.Action
	10, // 1: ffmpeg.DevicesResponse.devices:type_name -> ffmpeg.AudioDevice
	1,  // 2: ffmpeg.FFmpegService.StartStream:input_type -> ffmpeg.StreamRequest
	3,  // 3: ffmpeg.FFmpegService.StopStream:input_type -> ffmpeg.StreamControlRequest
	5,  // 4: ffmpeg.FFmpegService.AdjustLatency:input_type -> ffmpeg.LatencyRequest
	7,  // 5: ffmpeg.FFmpegService.ControlStream:input_type -> ffmpeg.ControlRequest
	9,  // 6: ffmpeg.FFmpegService.GetAudioDevices:input_type -> ffmpeg.DevicesRequest
	12, // 7: ffmpeg.FFmpegService.GetMediaProperties:input_type -> ffmpeg.MetadataRequest
	14, // 8: ffmpeg.FFmpegService.GetVideoScreenshot:input_type -> ffmpeg.ScreenshotRequest
	16, // 9: ffmpeg.FFmpegService.Shutdown:input_type -> ffmpeg.ShutdownRequest
	2,  // 10: ffmpeg.FFmpegService.StartStream:output_type -> ffmpeg.StreamResponse
	4,  // 11: ffmpeg.FFmpegService.StopStream:output_type -> ffmpeg.StreamControlResponse
	6,  // 12: ffmpeg.FFmpegService.AdjustLatency:output_type -> ffmpeg.LatencyResponse
	8,  // 13: ffmpeg.FFmpegService.ControlStream:output_type -> ffmpeg.ControlResponse
	11, // 14: ffmpeg.FFmpegService.GetAudioDevices:output_type -> ffmpeg.DevicesResponse
	13, // 15: ffmpeg.FFmpegService.GetMediaProperties:output_type -> ffmpeg.MetadataResponse
	15, // 16: ffmpeg.FFmpegService.GetVideoScreenshot:output_type -> ffmpeg.ScreenshotResponse
	17, // 17: ffmpeg.FFmpegService.Shutdown:output_type -> ffmpeg.ShutdownResponse
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_stream_proto_init() }
func file_proto_stream_proto_init() {
	if File_proto_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stream_proto_rawDesc), len(file_proto_stream_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_stream_proto_goTypes,
		DependencyIndexes: file_proto_stream_proto_depIdxs,
		EnumInfos:         file_proto_stream_proto_enumTypes,
		MessageInfos:      file_proto_stream_proto_msgTypes,
	}.Build()
	File_proto_stream_proto = out.File
	file_proto_stream_proto_goTypes = nil
	file_proto_stream_proto_depIdxs = nil
}
